package com.example.WebProject.DSA;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;

import com.example.WebProject.Repository.DSAKarmaRepository;

public class DSAKarmaDatabase {
    private static final Logger log = LoggerFactory.getLogger(DSAKarmaDatabase.class);

    @Bean
    CommandLineRunner initDatabase(DSAKarmaRepository repository) {
        return args -> {
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ANGRIFFSLUST", "(MU/MU/IN)", "2 Aktionen", "8", "8 Schritt", "10 KR", "Wesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ANGRIFFSWELLE", "(MU/IN/KO)", "2 Aktionen", "16", "32 Schritt", "sofort", "Wesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("AUGEDESJAEGERS", "(MU/IN/CH)", "4 Aktionen", "8", "selbst", "1 Stunde", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("AUSNUECHTERN", "(KL/IN/CH)", "4 Aktionen", "4", "Berührung", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BANNDERDUNKELHEIT", "(MU/KL/CH)", "1 Aktionen", "4 + 2 pro Minute", "selbst", "aufrechterhaltend", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BANNDERFURCHT", "(IN/CH/CH)", "2 Aktionen", "8", "Berührung", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BANNDERGOETTLICHENGABEN", "(KL/IN/CH)", "2 Aktionen", "8", "Berührung", "QSx10 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BANNDESLICHTS", "(MU/KL/CH)", "4 Aktionen", "16 +8 pro 5 Minuten", "selbst", "aufrechterhaltend", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BANNWIDERUNTOTE", "(MU/KL/CH)", "2 Aktionen", "8", "8 Schritt", "sofort", "Untote, außer Vampire")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BANNSTRAHL", "(MU/IN/CH)", "4 Aktionen", "16", "16 Schritt", "sofort", "Dämonen, Kulturschaffende (Paktierer mit entblößtem Dämonenmal)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BANNZONE", "(MU/IN/CH)", "4 Aktionen", "4 +2 pro 5 KR", "4 Schritt", "aufrechterhaltend", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BAERENHAUT", "(IN/CH/KO)", "2 Aktionen", "8", "selbst", "QSx2 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BEFEHLDESSCHAMANEN", "(MU/KL/CH)", "2 Aktionen", "16", "4 Schritt", "QS KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BEFREIUNGDESGEISTES", "(MU/IN/CH)", "4 Aktionen", "8", "Berührung", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BEGNADETERREITER", "(MU/IN/CH)", "2 Aktionen", "8", "selbst", "2 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BERAUSCHEN", "(MU/CH/KO)", "8 Aktionen", "8", "8 Schritt", "15 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BESAENFTIGUNG", "(MU/KL/CH)", "2 Aktionen", "2", "8 Schritt", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BESCHEIDENHEIT", "(MU/KL/CH)", "4 Aktionen", "4", "8 Schritt", "QS Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BESCHWOERUNGDERGEMEINENDIENERDESRATTENKINDES", "(MU/CH/KO)", "4 Aktionen", "8", "8 Schritt", "sofort", "Dämonen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BLENDSTRAHL", "(MU/KL/IN)", "1 Aktionen", "4", "8 Schritt", "QS in Kampfrunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BLENDUNG", "(MU/KL/CH)", "8 Aktionen", "16", "4 Schritt", "QSx5 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BLICKAUFDENMEERESGRUND", "(KL/IN/IN)", "1 Aktionen", "4", "selbst", "QSx2 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BLICKDESHEILERS", "(KL/IN/CH)", "4 Aktionen", "4", "selbst", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BLITZSCHLAG", "(MU/IN/CH)", "4 Aktionen", "16", "16 Schritt", "sofort", "Wesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BLUTIGERZORN", "(MU/IN/CH)", "2 Aktionen", "16", "8 Schritt", "10 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BLUTIGESSIEGEL", "(MU/IN/CH)", "8 Aktionen", "16", "Berührung", "QSx100 Jahre", "Objekte (Buch)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BLUTZOLL", "(MU/IN/CH)", "2 Aktionen", "16", "selbst", "QSx2 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BODENWEIHE", "(MU/IN/CH)", "4 Aktionen", "8", "8 Schritt", "QSx10 Minuten", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BOTSCHAFTAUSDERTIEFE", "(MU/IN/CH)", "16 Aktionen", "8", "selbst", "QS/2 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BRAZORAGHSKRIEGER", "(MU/MU/IN)", "2 Aktionen", "8", "8 Schritt", "QSx2 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BUECHERSUCHE", "(KL/KL/IN)", "16 Aktionen", "4", "selbst", "sofort", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("DAEMONENWALL", "(MU/KL/CH)", "1 Aktionen", "4", "selbst", "5 Minuten", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("DELPHINRUF", "(KL/IN/CH)", "4 Aktionen", "16", "selbst", "15 Minuten", "Tiere (Delphine)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("DESEINENBEZAUBERNDERSPHAERENKLANG", "(IN/CH/CH)", "1 Aktionen", "8", "8 Schritt", "QSx3 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("DOPPELGAENGER", "(MU/KL/IN)", "8 Aktionen", "16", "selbst", "QSx5 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("EHRENHAFTIGKEIT", "(MU/IN/CH)", "4 Aktionen", "8", "8 Schritt", "QSx3 in Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("EHRLICHERVERTRAG", "(KL/IN/CH)", "4 Aktionen", "8", "selbst", "2 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("EISBAERENRUF", "(MU/IN/CH)", "4 Aktionen", "16", "selbst", "15 Minuten", "Tiere(Eisbären)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ENTFESSELUNG", "(MU/KL/IN)", "2 Aktionen", "8", "4 Schritt", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ENTSTELLTESAMTLITZ", "(MU/IN/CH)", "4 Aktionen", "8", "8 Schritt", "2 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ENTZIFFERN", "(KL/KL/IN)", "8 Aktionen", "4", "selbst", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ERDBEBEN", "(MU/KL/IN)", "4 Aktionen", "16", "16 Schritt", "5 KR", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ERMUTIGUNG", "(MU/IN/CH)", "4 Aktionen", "8", "Berührung", "QSx3 Minuten", "Kulturschaffende, übernatürliche Wesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ERNUECHTERUNG", "(MU/KL/CH)", "2 Aktionen", "4", "selbst", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ERREGENDERRAUSCH", "(MU/IN/KO)", "8 Aktionen", "4", "selbst", "15 Minuten, danach wirkt Rauschmittel nicht mehr", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ERTRINKEN", "(MU/KL/KO)", "2 Aktionen", "4", "8 Schritt", "5 KR", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ERWACHEN", "(MU/IN/CH)", "2 Aktionen", "4", "16 Schritt", "sofort", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ERZENEOPFERGABE", "(MU/IN/CH)", "8 Aktionen", "8", "Berührung", "sofort", "Profane Objekte (Metalle und Steine)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FALLINSNICHTS", "(MU/IN/GE)", "1 Aktionen", "4", "selbst", "QSx9 KR", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FESSELNDESBAND", "(MU/IN/CH)", "1 Aktionen", "8", "16 Schritt", "QS KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FEUERWALL", "(MU/KL/CH)", "2 Aktionen", "16", "selbst", "5 Minuten", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FLUGECHSENRUF", "(MU/IN/CH)", "4 Aktionen", "16", "selbst", "15 Minuten", "Tiere (Flugechsen)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FREUNDSCHAFTLICHESAUFTRETEN", "(IN/CH/CH)", "4 Aktionen", "8", "selbst", "10 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FRIEDFERTIGKEIT", "(MU/IN/CH)", "4 Aktionen", "4 +2 pro 2 KR", "selbst", "aufrechterhaltend", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FRIEDVOLLEAURA", "(MU/IN/CH)", "1 Aktionen", "8", "selbst", "QSx3 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FRIEDVOLLERRAUSCH", "(MU/IN/CH)", "2 Aktionen", "8", "16 Schritt", "5 KR", "Kultruschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FROSTSTURM", "(MU/IN/CH)", "8 Aktionen", "8 +4 pro 5 Minuten", "selbst", "aufrechterhaltend", "selbst")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FURCHTEINFLOESSENDETIERGEISTER", "(MU/IN/CH)", "2 Aktionen", "8", "selbst", "5 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FURCHTRESISTENZ", "(MU/CH/KO)", "1 Aktionen", "8", "selbst", "QSx5 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GEBIETERDERFLAMMEN", "(MU/KL/IN)", "4 Aktionen", "4 +2 pro Minute", "selbst", "aufrechterhaltend", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GEFÜHLSKÄLTE", "(MU/IN/CH)", "4 Aktionen", "8", "selbst", "QS Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GEISTDESSTRATEGEN", "(MU/KL/IN)", "1 Aktionen", "8", "16 Schritt", "5 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GEISTERBLICK", "(MU/IN/CH)", "2 Aktionen", "4 +2 pro Minute", "selbst", "aufrechthaltend", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GEISTERFALLE", "(MU/IN/CH)", "8 Aktionen", "16", "8 Schritt", "sofort", "Geister")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GELDWECHSEL", "(KL/IN/FF)", "1 Aktionen", "1", "Berührung", "1 Jahr", "Objekte")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GESEGNETERRAUSCH", "(MU/IN/CH)", "8 Aktionen", "4", "Berührung", "QSx30 Minuten", "Profane Objekte (Rauschmittel)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GESPUERFUERDASGOETTLICHE", "(MU/IN/CH)", "16 Aktionen", "16", "Berührung", "sofort", "Objekte")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GETREIDEWACHSTUM", "(KL/IN/CH)", "16 Aktionen", "4", "Berührung", "sofort", "Pflanze (landwirtschaftlich genutztes Getreide)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GIFTBANN", "(KL/IN/CH)", "4 Aktionen", "8", "4 Schritt", "sofort", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GNADENSTOSS", "(MU/IN/CH)", "2 Aktionen", "8", "Berührung", "4 +QS/2 KR", "Geweihte Objekte (Marbodolch)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GOLDENEHAND", "(KL/IN/CH)", "4 Aktionen", "8", "Berührung", "QS Stunden", "Profane Objekte (maximal Apfelgröße)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GOLDENERUESTUNG", "(MU/KL/IN)", "1 Aktionen", "4 für RS 1, 8 für RS 2, 16 für RS 3", "selbst", "QSx3 Minuten", "Wesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GOETTLICHEKLINGE", "(MU/KL/IN)", "2 Aktionen", "8", "Berührung", "QSx2 KR", "Objekte (profane Objekt, Waffen)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GOETTLICHEVERSTAENDIGUNG", "(MU/IN/CH)", "4 Aktionen", "8", "selbst", "selbst", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GOETTLICHERFINGERZEIG", "(KL/IN/IN)", "4 Aktionen", "8", "selbst", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GOETTLICHERRAUSCH", "(MU/IN/CH)", "8 Aktionen", "8", "selbst", "QSx3 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GOETTLICHESZEICHEN", "(IN/IN/CH)", "4 Aktionen", "4", "4 Schritt", "sofort", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HAIRUF", "(MU/IN/CH)", "4 Aktionen", "16", "selbst", "15 Minuten", "Tiere (Streifenhaie)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HAUCHDESELEMENTS", "(MU/KL/CH)", "1 Aktionen", "8", "8 Schritt", "sofort", "Alle")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HEILIGERBEFEHL", "(MU/KL/CH)", "4 Aktionen", "16", "4 Schritt", "QSx2 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HEILIGESLIEBESSPIEL", "(MU/IN/CH)", "8 Aktionen", "4", "Berührung", "QSx30 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HEILSAMEQUELLE", "(KL/IN/CH)", "8 Aktionen", "8", "Berührung", "QS Minuten", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HEILSEGEN", "(KL/IN/CH)", "16 Aktionen", "1 pro LeP, mindestens 4", "Berührung", "sofort", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HELDENKRAFT", "(MU/IN/CH)", "2 Aktionen", "8", "selbst", "5 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HELFENDEHAND", "(KL/IN/CH)", "16 Aktionen", "8", "Berührung", "sofort (maximal 1 Woche)", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HERBEIRUFUNGDERHEERSCHARENDESRATTENKINDESRATTEN", "(MU/IN/CH)", "1 Aktionen", "8", "32 Schritt", "QSx3 Tage", "Tiere (Ratten)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HERBEIRUFUNGDERHEERSCHARENDESRATTENKINDESSCHAKALE", "(MU/IN/CH)", "2 Aktionen", "16", "32 Schritt", "QS Tage", "Tiere (Schakale)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HERBEIRUFUNGDERHEERSCHARENDESRATTENKINDESVAMPIRFLEDERMAEUSE", "(MU/IN/CH)", "1 Aktionen", "8", "32 Schritt", "QSx3 Tage", "Tiere (Vampirfledermaeuse)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HERBEIRUFUNGDERHEERSCHAFENDESRATTENKINDESWOLFSSPINNEN", "(MU/IN/CH)", "2 Aktionen", "16", "32 Schritt", "QS Tage", "Tiere (wolfsspinnen)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HERBEIRUFUNGVONTAIRACHSDIENERNNEBELKRAEHEN", "(MU/IN/CH)", "2 Aktionen", "8", "32 Schritt", "QS Tage", "Tiere (Nebelkrähen)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HERRDERFLAMMEN", "(MU/IN/CH)", "8 Aktionen", "8", "selbst", "QSx30 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HILFREICHESEELE", "(MU/IN/CH)", "4 Aktionen", "4", "8 Schritt", "QS Schritt", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("INNERERUHE", "(MU/KL/IN)", "4 Aktionen", "8", "selbst", "5 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("JAGUARRUF", "(MU/IN/CH)", "4 Aktionen", "16", "selbst", "15 Minuten", "Tiere (Jaguare)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KAELTEEXPLOSION", "(MU/IN/KO)", "2 Aktionen", "8", "16", "sofort", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KAMPFGESCHICK", "(MU/IN/KO)", "1 Aktionen", "4", "selbst", "QSx2 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KLARERGEIST", "(MU/KL/IN)", "4 Aktionen", "8", "Berührung", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KLEIDUNGSCHAMAELEON", "(KL/IN/CH)", "2 Aktionen", "4", "Berührung", "QS Stunden", "Objekte (Kleidung)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KLEINEWINDHOSE", "(MU/CH/KO)", "1 Aktionen", "8", "16 Schritt", "sofort", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KLEINERBANNWIDERUNTOTE", "(MU/MU/CH)", "1 Aktionen", "4", "8 Schritt", "sofort", "Untote (Vampire sind immun)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KLEINERBANNSTRAHL", "(MU/IN/CH)", "2 Aktionen", "8", "16 Schritt", "sofort", "Dämonen, Kulturschaffende (Paktierer mit entblößtem Dämonenmal)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KRAFTVOLLERKOERPER", "(MU/IN/KO)", "4 Aktionen", "8", "selbst", "QSx5 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KRANKHEITENVORBEUGEN", "(IN/IN/CH)", "8 Aktionen", "8", "selbst", "QS Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KRANKHEITSBANN", "(KL/IN/CH)", "4 Aktionen", "8", "4 Schritt", "sofort", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KRIEGSFARBEN", "(MU/IN/KO)", "2 Aktionen", "4", "selbst", "5 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("LAUTLOS", "(IN/IN/GE)", "4 Aktionen", "4 +2 pro Minute", "selbst", "aufrechterhaltend", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("LEBENSSCHUTZ", "(MU/KL/IN)", "2 Aktionen", "8", "Berührung", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("LEVTHANISCHERLIEBHABER", "(MU/IN/CH)", "4 Aktionen", "8", "selbst", "QS Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("LITURGIESCHILD", "(MU/KL/CH)", "2 Aktionen", "4", "selbst", "10 Minuten", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("LUSTERZEUGEN", "(MU/IN/CH)", "1 Aktionen", "4", "4 Schritt", "QSx3 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MACHTDESLEVTHAN", "(MU/CH/KO)", "4 Aktionen", "16", "selbst", "QSx3 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MAECHTIGERANGRIFF", "(MU/IN/KO)", "2 Aktionen", "8", "selbst", "QSx3 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MAGIEANALYSE", "(KL/KL/IN)", "32 Aktionen", "16", "Berührung", "sofort", "Objekte, Wesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MAGIEBANN", "(KL/IN/CH)", "4 Aktionen", "8 bzw 16 für Zone", "Berührung", "sofort", "Alle")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MAGIESCHUTZ", "(MU/IN/CH)", "4 Aktionen", "8 +4 pro 10 Minuten", "selbst", "aufrechterhaltend", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MAGIESICHT", "(KL/IN/IN)", "2 Aktionen", "4", "8 Schritt", "1 Minute", "Lebewesen, Objekte")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MAGIESPIEGEL", "(MU/KL/IN)", "2 Aktionen", "8", "selbst", "QS KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MAMMUTRUF", "(MU/IN/CH)", "4 Aktionen", "32", "selbst", "15 Minuten", "Tiere (Mammuts)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MASKE", "(KL/IN/CH)", "4 Aktionen", "8", "selbst", "30 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MAUEREINSTURZ", "(MU/IN/CH)", "4 Aktionen", "16", "4 Schritt", "sofort", "Objekte (Mauer)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MEERESUNGEHEUERVERTREIBEN", "(MU/IN/CH)", "16 Aktionen", "16 bis groß, 32 für riesig", "16 Schritt", "sofort", "Lebewesen (Meeresungeheuer)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MITDUMMHEITSCHLAGEN", "(KL/IN/CH)", "2 Aktionen", "8", "Berührung", "2 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MONDSICHT", "(KL/KL/IN)", "4 Aktionen", "2 +1 pro 10 Minuten", "selbst", "aufrechterhaltend", "Wesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MONDSILBERZUNGE", "(KL/IN/CH)", "1 Aktionen", "8", "selbst", "QSx3 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MOTIVATION", "(MU/IN/CH)", "4 Aktionen", "4", "Berührung", "2 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("NAMENLOSEKAELTE", "(KL/IN/CH)", "4 Aktionen", "16", "selbst", "30 Minuten", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("NAMENLOSERASEREI", "(MU/IN/CH)", "4 Aktionen", "16", "8 Schritt", "sofort", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("NAMENLOSEZWEIFEL", "(MU/IN/CH)", "4 Aktionen", "16", "16 Schritt", "QSx3 Tage", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("NAMENLOSESVERGESSEN", "(KL/IN/CH)", "2 Aktionen", "8", "Berührung", "QSx3 Tage", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("NABELKRAEHENSCHWARM", "(MU/KL/IN)", "2 Aktionen", "8", "selbst", "12 Stunden", "Kulturschaffende (nur Schamane selbst)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("NUMINORUSFESSELN", "(MU/KL/KK)", "2 Aktionen", "8", "8 Schritt", "QS +1", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("OBARANSBLENDUNG", "(MU/KL/CH)", "4 Aktionen", "16", "16 Schritt", "QSx5 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("OBJEKTSEGEN", "(MU/IN/CH)", "4 Aktionen", "4", "Berührung", "QSx3 Stunden", "Objekte")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("OBSESSION", "(KL/IN/CH)", "4 Aktionen", "8", "Berührung", "30 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("OFFENLEGUNGDESGEISTES", "(KL/IN/CH)", "2 Aktionen", "8 +4 pro 30 Sekunden", "Berührung", "aufrechterhaltend", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("OGERRUF", "(KL/IN/CH)", "4 Aktionen", "16", "selbst", "QS Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("OPFERGANG", "(MU/KO/KK)", "4 Aktionen", "16", "selbst", "ein Kampf, maximal 2 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ORTDERRUHE", "(MU/KL/IN)", "8 Aktionen", "4", "4 Schritt", "QSX3 Stunden", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("PECHUNDSCHWEFEL", "(MU/KL/CH)", "2 Aktionen", "8", "16 Schritt", "sofort", "Alle")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("PERAINESGNADE", "(IN/CH/FF)", "2 Aktionen", "8", "Berührung", "QS KR", "'Objekte (Samenkorn)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("PFLANZENWUCHS", "(KL/IN/CH)", "16 Aktionen", "8", "Berührung", "1 Jahr", "Pflanze")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("QUALLENHAUT", "(MU/KL/KK)", "2 Aktionen", "16", "selbst", "QSx3 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("QUALLENRUF", "(MU/IN/CH)", "4 Aktionen", "16", "selbst", "15 Minuten", "Tiere (Quallen)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("RABENRUF", "(MU/KL/IN)", "16 Aktionen", "8", "QSx3 Meilen", "QSx3 Stunden", "Tiere")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("RATTENSCHWARM", "(MU/KL/IN)", "2 Aktionen", "8", "selbst", "13 Stunden", "Kulturschaffende (nur der geweihte selbst)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("REGENBOGENBRUECKE", "(MU/IN/KO)", "4 Aktionen", "8", "selbst", "QSx3 Minuten", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("REINIGUNGDESBOESEN", "(MU/IN/CH)", "8 Aktionen", "8", "4 Schritt", "sofort", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("RINDERRUF", "(MU/IN/CH)", "4 Aktionen", "16", "selbst", "15 Minuten", "Tiere ((Ongalo-) Rinder")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("RUFDERHEIMAT", "(KL/IN/CH)", "8 Aktionen", "4", "selbst", "QSx30 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHATTENFESSEL", "(MU/IN/KO)", "4 Aktionen", "8", "16 Schritt", "QS/2 KR", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHIFFSGESPUER", "(KL/IN/IN)", "4 Aktionen", "4", "50 Meilen", "QS Minuten", "Objekte (Schiff)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHLAF", "(KL/IN/CH)", "2 Aktionen", "8", "8 Schritt", "QSx3 Minuten", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHLANGENRUF", "(MU/IN/CH)", "4 Aktionen", "8", "selbst", "15 Minuten", "Tiere (Würgeschlangen)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHLANGENSTAB", "(MU/KL/IN)", "2 Aktionen", "8", "4 Schritt", "QSx3 Minuten", "Objekte")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHLANGENZUNGE", "(MU/KL/IN)", "4 Aktionen", "8", "selbst", "QSx3 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHLEICHENDEFAEULNIS", "(MU/IN/KO)", "2 Aktionen", "16", "Berührung", "QS Tage", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHLEICHENDEFAEULNISPFLANZEN", "(KL/IN/CH)", "2 Aktionen", "2 (Pflanzen), 8 (Pflanzenwesen)", "4 Schritt", "sofort", "Pflanze")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHLINGERRUF", "(MU/IN/CH)", "4 Aktionen", "32", "selbst", "15 Minuten", "Tiere (Schlinger)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHMERZRESISTENZ", "(MU/IN/KO)", "1 Aktion", "8", "selbst", "QSx3 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHONFRIST", "(KL/IN/CH)", "2 Aktionen", "8", "Berührung", "QSx3 KR", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHUTZDERHORNISSENKOENIGING", "(KL/IN/KO)", "2 Aktionen", "16", "8 Schritt", "10 Minuten", "Kulturschaffende (nur Freiwillige)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHUTZDERWEHRLOSEN", "(MU/IN/CH)", "1 Aktionen", "8", "16 Schritt", "QSx3 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHUTZSEGEN", "(MU/IN/CH)", "4 Aktionen", "4 +2 pro 5 KR", "4 Schritt", "aufrechterhaltend", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHWINDENDEZAUBERKRAFT", "(IN/IN/CH)", "2 Aktionen", "16", "4 Schritt", "QSx3 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SEELENSCHATTEN", "(MU/IN/CH)", "2 Aktionen", "8 +4 für 5 Stunden", "selbst", "aufrechterhaltend", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SEEVOGELSPRACHE", "(KL/IN/CH)", "4 Aktionen", "8", "selbst", "QSx3 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SICHERERWEG", "(MU/KL/IN)", "8 Aktionen", "4", "selbst", "aufrechterhaltend", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SICHTINDERDUNKELHEIT", "(KL/IN/KO)", "4 Aktionen", "2 +1 pro 10 Minuten", "selbst", "aufrechterhaltend", "Wesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SPEERDERATHLETEN", "(MU/IN/KK)", "2 Aktionen", "8", "16 Schritt", "sofort", "Wesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SPRACHEDESTAPAMS", "(KL/IN/CH)", "8 Aktionen", "16", "Berührung", "5 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("STEINHAUT", "(IN/CH/KO)", "2 Aktionen", "16", "selbst", "QSx2 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("STERNENGLANZ", "(KL/IN/CH)", "2 Aktionen", "8", "8 Schritt", "QSx15 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("STURMRUF", "(MU/IN/CH)", "8 Aktionen", "8 +4 pro 5 KR", "selbst", "aufrechterhaltend", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("TALISMANRUF", "(KL/IN/CH)", "4 Aktionen", "32", "selbst", "QS Stunden", "Objekte (Talismane)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("TIERBEHERRSCHUNG", "(MU/IN/CH)", "2 Aktionen", "8", "8 Schritt", "QSx3 Minuten", "Tiere (nur Landtiere)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("TIEREBERUHIGEN", "(MU/IN/CH)", "2 Aktionen", "4", "8 Schritt", "QSx3 Minuten", "Tiere")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("TIERLEIDLINDERN", "(MU/IN/CH)", "8 Aktionen", "8", "Berührung", "sofort", "Tiere")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("TIERSPRACHE", "(MU/IN/CH)", "4 Aktionen", "8", "selbst", "QS Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("TRANKFLUCH", "(KL/IN/CH)", "2 Aktionen", "8", "Berührung", "sofort", "Objekte (Tränke, Flüssigkeiten)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("TREUERBEGLEITER", "(MU/KL/IN)", "8 Aktionen", "4", "selbst", "QS/2 Tage", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("TSAGEDANKENSPIEL", "(MU/KL/IN)", "2 Aktionen", "8", "4 Schritt", "5 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("UNSICHTBAREFLUT", "(MU/KL/KO)", "4 Aktionen", "16", "selbst", "5 KR", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("UNTERWASSERATMUNG", "(MU/IN/KO)", "4 Aktionen", "4 +2 pro 15 Minuten", "selbst", "aufrechterhaltend", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("UNTOTENERHEBUNG", "(MU/KL/CH)", "2 Aktionen", "8", "8 Schritt", "QSx2 KR", "Kulturschaffende (Verstorbene)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("VAMPIRISCHEKRAEFTE", "(MU/IN/KO)", "4 Aktionen", "16", "selbst", "5 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("VERSTECKTESBEGEHREN", "(MU/IN/CH)", "1 Aktionen", "8", "Berührung", "5 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("VERSTEINERUNG", "(MU/KL/IN)", "4 Aktionen", "16", "4 Schritt", "QSx3 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("WAHRHEIT", "(MU/KL/IN)", "8 Aktionen", "16", "Berührung", "QSx3 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("WANDWIDERDAEMONEN", "(MU/KL/CH)", "2 Aktionen", "4", "selbst", "10 Minuten", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("WASSERLAUF", "(MU/IN/GE)", "8 Aktionen", "8", "selbst", "QSx3 Minuten", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("WEIHEDESBODENS", "(MU/IN/CH)", "4 Aktionen", "4", "8 Schritt", "QS Minuten", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("WIESELFLINK", "(IN/IN/GE)", "2 Aktionen", "8", "selbst", "QSx3 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("WINDHOSE", "(MU/CH/KO)", "2 Aktionen", "8", "16 Schritt", "sofort", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("WINDRUF", "(MU/IN/CH)", "8 Aktionen", "8", "selbst", "30 Minuten", "Profane Objekte (Segel)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("WOLFSRUF", "(MU/IN/CH)", "4 Aktionen", "16", "selbst", "15 Minuten", "Tiere (Wölfe)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("WUNDERSAMEVERSTAENDIGUNG", "(KL/KL/IN)", "2 Aktionen", "8", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ZAEHEHAUT", "(MU/IN/KO)", "1 Aktionen", "4", "selbst", "QSx2 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ZAUBERSCHUTZ", "(MU/KL/CH)", "1 Aktionen", "8", "selbst", "5 Minuten", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ZWERGENMACHT", "(MU/IN/KO)", "8 Aktionen", "8", "Berührung", "30 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("EIDSEGEN", "-", "0 Aktionen", "0", "4 Schritt", "1 Jahr", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FEUERSEGEN", "-", "0 Aktionen", "0", "selbst", "5 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GEBURTSSEGEN", "-", "0 Aktionen", "0", "Berührung", "Bei Zwölfgötterkirche und menschlichen Kulten bis zum 12. Lebensjahr, bei Achaz bis zur zweiten Häutung, bei Zwergen bis zur Feuertaufe", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GLUECKSSEGEN", "-", "0 Aktionen", "0", "Berührung", "12 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GRABSEGEN", "-", "0 Aktionen", "0", "Berührung", "12 Monate", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HARMONIESEGEN", "-", "0 Aktionen", "0", "Berührung", "12 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KLEINERHEILSEGEN", "-", "0 Aktionen", "0", "Berührung", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KLEINERSCHUTZSEGEN", "-", "0 Aktionen", "0", "4 Schritt", "4 KR", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("Speisesegen", "-", "0 Aktionen", "0", "Berührung", "sofort", "Objekte")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("STAERKUNGSSEGEN", "-", "0 Aktionen", "0", "selbst", "12 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("TRANKSEGEN", "-", "0 Aktionen", "0", "Berührung", "sofort", "Objekte")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("WEISHEITSSEGEN", "-", "0 Aktionen", "0", "Berührung", "12 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ALVERANSFEDER", "-", "0 Aktionen", "16", "-", "1 Stunde", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("AUGEDESPRAIOS", "-", "0 Aktionen", "8", "-", "1 Stunde", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("DELPHINSTAB", "-", "0 Aktionen", "8", "-", "1 Stunde", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("DERHEILIGEEINSKRISTALL", "-", "0 Aktionen", "8", "-", "24 Stunde", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("DIEEISROSEVONJARLAK", "-", "0 Aktionen", "8", "-", "1 Monat", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("DSCHADRAALZUL", "-", "0 Aktionen", "8", "-", "1 Stunde", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("EFFERDHORNVONRETHIS", "-", "0 Aktionen", "8", "-", "5 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("EFFERDPERLE", "-", "0 Aktionen", "8", "-", "QS Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("EIDECHSENAUGE", "-", "0 Aktionen", "8", "-", "1 Stunde", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("EIJASTROMMEL", "-", "0 Aktionen", "8", "-", "6 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ERSTERSCHLEIER", "-", "0 Aktionen", "8", "-", "QS Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GOLDENEEI", "-", "0 Aktionen", "8", "-", "24 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HANDSCHUHDERPERAINE", "-", "0 Aktionen", "8", "-", "1 Stunde", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HEILIGELATERNEZUANGBAR", "-", "0 Aktionen", "8", "-", "6 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HEILIGEREISKRISTALL", "-", "0 Aktionen", "8", "-", "24 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HEILIGERKESSEL", "-", "0 Aktionen", "8", "-", "24 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HEILIGESSCHWERTRABENFEDER", "-", "0 Aktionen", "8", "-", "1 Stunde", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HONINGERTIEGEL", "-", "0 Aktionen", "8", "-", "1 Stunde", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("INFUNDIBULUMDERALLWISSENDEN", "-", "0 Aktionen", "4", "-", "1 Stunde", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("JOBORNERLIEBESLICHT", "-", "0 Aktionen", "8", "-", "4 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KELCHDERRAHJA", "-", "0 Aktionen", "8", "-", "24 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KREIDEDERTSA", "-", "0 Aktionen", "8", "-", "24 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KRUGDERHEILIGENLINDEGARD", "-", "0 Aktionen", "8", "-", "24 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("LAPISLAZULIFLOETE", "-", "0 Aktionen", "8", "-", "QSx10 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("LEVTHANSBAND", "-", "0 Aktionen", "8", "-", "1 Stunde", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("LICHTDERPALLINAI", "-", "0 Aktionen", "8", "-", "QS Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MANTELDERHEILIGENMASCHA", "-", "0 Aktionen", "8", "-", "6 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MONDSILBERSCHLUESSEL", "-", "0 Aktionen", "8", "-", "6 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("PHEXENSSCHATTENRAUM", "-", "0 Aktionen", "8", "-", "10 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("RINGDESFIRUN", "-", "0 Aktionen", "8", "-", "6 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("RUDERBLATTDERJURGA", "-", "0 Aktionen", "8", "-", "24 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SAATDESLEBENS", "-", "0 Aktionen", "8", "-", "1 Stunde", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHLANGENSTABDESERZHEILIGENARGELION", "-", "0 Aktionen", "8", "-", "5 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHLEIERDERGLEICHMUT", "-", "0 Aktionen", "8", "-", "1 Stunde", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHWARZERSPEER", "-", "0 Aktionen", "8", "-", "1 Stunde", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("STEINDESINGERIMM", "-", "0 Aktionen", "8", "-", "24 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("TAFELDERHEILIGENCANYZETH", "-", "0 Aktionen", "8", "-", "24 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("WASSERKRUGDESEFFERD", "-", "0 Aktionen", "4", "-", "5 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("WUNDERSAMERUESTUNG", "-", "0 Aktionen", "8", "-", "1 Stunde", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("WURFSTERNDESPHEX", "-", "0 Aktionen", "8", "-", "1 Stunde", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ZWEIHAENDERARMALION", "-", "0 Aktionen", "8", "-", "1 Stunde", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ZWOELFTRAENENDEREFFERDANE", "-", "0 Aktionen", "4", "-", "QSx10 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("AECHTUNG", "(MU/IN/CH)", "30 Minuten", "16, davon 2 permanent", "Berührung", "permanent, bzw. biszur Buße", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ACKERSEGEN", "(MU/KL/IN)", "2 Stunden", "16", "Sicht", "ein Wachstumszyklus (zwischen 6 und 12 Monate)", "Pflanze")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ARCANUMINTERDICTUM", "(MU/IN/CH)", "8 Stunden", "128, davon 32 permanent", "selbst", "QS Monate", "Zone (Stadt)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("AUFNAHME", "(KL/IN/CH)", "30 Minuten", "8, davon 1 permanent", "Berührung", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("AUSBRENNEN", "(MU/KL/CH)", "2 stunden", "32, davon 4 permanent", "Berührung", "permanent", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BANNFLUCHANATHEMA", "(MU/IN/CH)", "8 Stunden", "128, davon 12 permanent", "Berührung", "permanent", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BERAUSCHENDERWEIN", "(MU/IN/CH)", "5 Minuten", "4", "Berührung", "sofort", "Objekte (profane Objekte, Wasser)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BESCHWOERUNGDERHOHENDIENERDESRATTENKINDES", "(MU/CH/KO)", "5 Minuten", "16", "8 Schritt", "sofort", "Dämonen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BESCHWOERUNGDERMACHTVOLLENDIENERDESRATTENKINDES", "(MU/CH/KO)", "30 Minuten", "32", "8 Schritt", "sofort", "Dämonen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BILDFUERDIEEWIGKEIT", "(MU/KL/IN)", "30 Minuten", "4", "selbst", "QSx2 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BLICKINDIEFLAMMEN", "(MU/KL/IN)", "5 Minuten", "2", "4 Schritt", "sofort", "Alle")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("DAEMONENPAKTBRECHEN", "(MU/IN/CH)", "8 Stunden", "32, davon 8 permanent", "Berührung", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("DASLOECHENDESLICHTS", "(MU/IN/CH)", "8 Stunden", "32", "Berührung", "sofort", "Objekte (Gwen-Petryl-Steine)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("DELPHINGESTALT", "(MU/KL/IN)", "30 Minuten", "16", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("DIENERDERERDE", "(MU/IN/CH)", "5 Minuten", "8", "selbst", "sofort", "Elementare (Humus)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("DIENERDERFLAMMEN", "(MU/IN/CH)", "5 Minuten", "8", "selbst", "sofort", "Elementare (Feuer)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("DIENERDERKAELTE", "(MU/IN/CH)", "5 Minuten", "8", "selbst", "sofort", "Elementare (Eis)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("DIENERDERWELLEN", "(MU/IN/CH)", "5 Minuten", "8", "selbst", "sofort", "Elementare (Wasser)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("DIENERDERWOLKEN", "(MU/IN/CH)", "5 Minuten", "8", "selbst", "sofort", "Elementare (Luft)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("DIENERDESERZES", "(MU/IN/CH)", "5 Minuten", "8", "selbst", "sofort", "Elementare (Erz)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("EIDECHSENGESTALT", "(MU/KL/IN)", "30 Minuten", "8", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("EIDECHSENREGENERATION", "(IN/CH/KO)", "30 Minuten", "8", "selbst", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("EINFLUESTERUNG", "(KL/IN/CH)", "30 Minuten", "8", "selbst", "QS Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("EINGESCHWORENEMANNSCHAFT", "(MU/KL/IN)", "30 Minuten", "32", "16 Schritt", "QS Tage", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("EINHORNGESTALT", "(MU/KL/IN)", "2 Stunden", "32", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("EISBAERENGESTALT", "(MU/KL/IN)", "30 Minuten", "16", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ELSTERNGESTALT", "(MU/KL/IN)", "30 Minuten", "8", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("EMPFAENGNISDESKORSMALS", "(MU/IN/KO)", "2 Stunden", "32", "32 Schritt", "9 Jahre", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ERFOLGREICHEPFLANZENSUCHE", "(KL/IN/KO)", "30 Minuten", "4", "selbst", "QS/3 Pflanzensuchen", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ERINNERN", "(MU/KL/IN)", "30 Minuten", "8", "selbst", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ERSCHAFFUNGVONNACHTKINDERN", "(MU/IN/CH)", "8 Stunden", "32, 8 permanent", "Berührung", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("EXORZISMUS", "(MU/IN/CH)", "8 Stunden", "8", "4 Schritt", "sofort", "Dämonen, Geister")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FALKENGESTALT", "(MU/KL/IN)", "30 Minuten", "8", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FESTDERFREUDE", "(MU/IN/CH)", "30 Minuten", "8", "selbst", "6 Stunden", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FLUGECHSENGESTALT", "(MU/KL/IN)", "30 Minuten", "8", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FREIESEELENFAHRT", "(MU/IN/CH)", "2 Stunden", "8", "selbst", "Qsx2 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FROSTSCHUTZ", "(MU/KL/IN)", "5 Minuten", "4 +2 pro 30 Minuten", "selbst", "aufrechterhaltend", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FRUCHTBARKEIT", "(MU/IN/CH)", "30 Minuten", "4", "Berührung", "QS/2 Tage", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FUCHSGESTALT", "(MU/KL/IN)", "30 Minuten", "8", "selsbt", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GAENSEGESTALT", "(MU/KL/IN)", "30 Minuten", "8", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GEIERGESTALT", "(MU/KL/IN)", "30 Minuten", "8", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GEISTERSPRACHE", "(MU/KL/CH)", "30 Minuten", "16", "selbst", "QSx10 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GEISTHEILUNG", "(KL/CH/KO)", "5 Minuten", "4", "Berührung", "24 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GESCHLECHTERWECHSEL", "(MU/IN/KO)", "2 Stunden", "16", "Berührung", "QSx3 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GESCHWINDERSCHRITT", "(MU/IN/CH)", "5 Minuten", "4", "selbst", "8 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GESPRAECHMITDEMTOTEN", "(MU/KL/IN)", "2 Stunden", "16", "selbst", "QS Minuten", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GEWEIHTERPANZER", "(MU/IN/CH)", "30 Minuten", "16", "selbst", "QSx30 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GNADEDESVERGESSENS", "(MU/IN/CH)", "30 Minuten", "8", "Berührung", "1 Jahr", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GOETTLICHEERKENNTNIS", "(KL/IN/CH)", "5 Minuten", "4", "selbst", "QSx30 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GOETTLICHEPRAEZISION", "(MU/IN/KO)", "30 Minuten", "16", "Berührung", "QSx30 Minuten", "Objekte")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GREIFENRUF", "(KL/IN/CH)", "8 Stunden", "8", "selbst", "QSx30 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GROSSEWAFFENWEIHE", "(MU/IN/CH)", "2 Stunden", "64, 4 permanent", "16 Schritt", "1 Monat", "Objekte (waffen)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GUTERFANG", "(IN/CH/KO)", "5 Minuten", "4", "Berührung", "QS Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HAEUTUNG", "(MU/IN/CH)", "32 Stunden", "32, davon 2 permanent", "selbst", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HEILIGERSCHWUR", "(MU/KL/CH)", "5 Minuten", "8", "Berührung", "bis Schwer endet", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HEILSCHLAF", "(MU/CH/KO)", "5 Minuten", "4", "Berührung", "24 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HEILUNGVONSEELENKRANKEN", "(MU/IN/CH)", "30 Minuten", "16", "Berührung", "24 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HERRDERMEERE", "(MU/IN/CH)", "30 Minuten", "16", "Berührung", "8 Stunden bzw. eien Tagesstrecke", "Objekte (profane Objekte, Wasserfahrzeuge)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HILFEINDERNOT", "(KL/IN/CH)", "5 Minuten", "4", "selbst", "QSx30 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HIMMLISCHESCHATZKAMMER", "(MU/IN/CH)", "5 Minuten", "16", "Berührung", "bis Phex entscheidet den Gegenstand fallen zu lassen", "Objekte")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HUNDEGESTALT", "(MU/KL/IN)", "30 Minuten", "8", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("INSPIRATION", "(MU/KL/IN)", "5 Minuten", "8", "selbst", "6 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("JAGDGLUECK", "(MU/IN/CH)", "5 Minuten", "4", "selbst", "QS Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("JAGUARGESTALT", "(MU/KL/IN)", "30 Minuten", "8", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("JUGENDLICHKEIT", "(MU/IN/CH)", "32 Stunden", "32", "selbst", "QS Monate", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KLEINEMORALSTAERKUNG", "(MU/IN/CH)", "30 Minuten", "16", "32 Schritt", "QS Tage", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KRIEGSZUSTAND", "(MU/IN/CH)", "8 Stunden", "128, 16 permanent", "ganz Dere", "bis zur Aufhebuzng durch Schwert der Schwerter, längstens jedoch 1 Monat", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("LAEUTERUNGDESERZES", "(MU/KL/IN)", "30 Minuten", "16", "selbst", "sofort", "Objekte (profane Objekte, erzene Materialien)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("LEBENSTAUSCH", "(MU/IN/KO)", "5 Minuten", "8", "Berührung", "sofort", "Tiere")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("LEICHTFUESSIG", "(IN/CH/GE)", "30 Minuten", "16", "selbst", "8 Stunden (1 Reisetag)", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("LEITENDESTROEMUNG", "(KL/KL/IN)", "30 Minuten", "16", "Berührung", "QS Stunden", "Objekte (Schiff)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("LIEBETAETOWIERUNG", "(IN/CH/FF)", "8 Stunden", "16", "Berührung", "QS Jahre", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("LITURGIEABSORPTION", "(MU/MU/IN)", "2 Stunden", "16", "16 Schritt", "13 Stunden", "Liturgien, Zeremonien")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("LOEWENGESTALT", "(MU/KL/IN)", "30 Minuten", "16", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("LUCHSGESTALT", "(MU/KL/IN)", "30 Minuten", "8", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MACHTVOLLEREXORZISMUS", "(MU/IN/CH)", "5 Minuten", "8 für niedrige geister und Dämonen, 16 für mittlere Geister und Dämonen mit bis zu 5 Hörnern, 32 für hohe Geister und Dämonen ab 6 Hörnern", "8 Schritt", "sofort", "Dämonen, Geister")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MAKELLOSERLEIB", "(MU/IN/CH)", "5 Minuten", "8", "Berührung", "QS Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MARBIDENMACHT", "(MU/KL/CH)", "30 Minuten", "8", "selbst", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("METALLERHITZUNG", "(MU/KL/IN)", "30 Minuten", "4", "Berührung", "QSx2 Stunden", "Profane Objekte (Metall)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MORALSTAERKUNG", "(MU/IN/CH)", "2 Stunden", "16", "32 Schritt", "QSx3 Tage", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MUNGOGESTALT", "(MU/KL/IN)", "30 Minuten", "8", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("NAHRUNGSREINIGUNG", "(MU/KL/IN)", "5 Minuten", "4", "8 Schritt", "sofort", "Profane Objekte (Nahrungsmittel)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("NEBELLEIB", "(KL/IN/CH)", "30 Minuten", "16", "selbst", "QSx10 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("NEBELSCHWADEN", "(IN/CH/KO)", "30 Minuten", "32", "selbst", "QS Stunden", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("NUMINORUSFLUCH", "(MU/CH/KO)", "16 Stunden", "16 pro angefangene 20 Schritt Länge des Wasserfahrzeugs", "Berührung", "QS Tage", "Objekte (Wasserfahrzeug)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("OBJEKTWEIHE", "(KL/IN/CH)", "2 Stunden", "16, davon 2 permanent", "4 Schritt", "permanent", "Objekte")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("OGERBINDUNG", "(MU/IN/CH)", "2 Stunden", "32, davon 8 permanent", "Berührung", "permanent", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ORTSWEIHESANCTUM", "(MU/IN/CH)", "8 Stunden", "64, davon 16 permanent", "8 Schritt", "permanent", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("PANTHERGESTALT", "(MU/KL/IN)", "30 Minuten", "16", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("PARADIESVOGELGESTALT", "(MU/KL/IN)", "30 Minuten", "8", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("PFERDEGESTALT", "(MU/KL/IN)", "30 Minuten", "16", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("PFLANZENKRAFT", "(KL/IN/IN)", "2 Stunden", "4", "Berührung", "sofort", "Pflanze")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("PRIESTERWEIHE", "(MU/IN/CH)", "8 Stunden", "32, davon 12 permanent", "Berührung", "permanent", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("RABENGESTALT", "(MU/KL/IN)", "30 Minuten", "8", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("RATDERAHNEN", "(MU/IN/CH)", "5 Minuten", "8", "selbst", "sofort", "Geister")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("REGENKONTROLLE", "(MU/IN/CH)", "30 Minuten", "16", "32 Schritt", "QSxStunden", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("REISESEGEN", "(MU/IN/CH)", "5 Minuten", "8", "Berührung", "QSx12 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SAETTIGUNG", "(MU/KL/CH)", "30 Minuten", "8", "4 Schritt", "12 Stunden", "Objekte (profane Objekte, Nahrungsmittel)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHAFFENSKRAFT", "(IN/CH/FF)", "2 Stunden", "8", "8 Schritt", "QS/2 Tage", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHATTENROCHENGESTALT", "(MU/KL/IN)", "30 Minuten", "16", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHLANGENFLUCH", "(MU/KL/CH)", "2 Stunden", "16", "Berührung", "QSx3 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHLANGENGESTALT", "(MU/KL/IN)", "30 Minuten", "8", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHMETTERLINGSGESTALT", "(MU/KL/IN)", "30 Minuten", "8", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SCHWANENGESTALT", "(MU/KL/IN)", "30 Minuten", "8", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SEELENBANNUNG", "(MU/IN/CH)", "16 Stunden", "32", "4 Schritt", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SEELENPRUEFUNG", "(MU/KL/IN)", "5 Minuten", "8", "4 Schritt", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SEEMONSTERRUF", "(MU/CH/KO)", "5 Minuten", "32", "64 Schritt", "2 Stunden", "Lebewesen (Meeresungeheuer)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SEGNUNGDESHEIMS", "(MU/IN/CH)", "30 Minuten", "16", "Berührung", "QS Tage", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SELBSTOPFERUNG", "(MU/MU/KO)", "2 Stunden", "32", "Berührung", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SICHERERTRITT", "(IN/CH/GE)", "5 Minuten", "8+ 4 pro 4 Stunden", "selbst", "aufrechterhaltend", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SIPPENBANN", "(MU/IN/CH)", "5 Minuten", "16, davon 2 permanent", "Berührung", "permanent", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("SPEISUNG", "(MU/IN/CH)", "30 Minuten", "16", "8 Schritt", "1 Tag", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("STAERKUNGDERWILDNIS", "(MU/IN/KO)", "5 Minuten", "8", "selbst", "QSx3 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("STAUBUNDSCHIMMEL", "(IN/CH/KO)", "5 Minuten", "2/4/8/16 für Objekt der Größe Tasse/Truhe/Tür/Burgtor", "Berührung", "permanent", "Profane Objekte")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("STORCHENGESTALT", "(MU/KL/IN)", "30 Minuten", "8", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("TABUZONE", "(KL/IN/CH)", "2 Stunden", "16", "8 Schritt", "1 Monat", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("TAIRACHSMACHTVOLLEERHEBUNGVONUNTOTEN", "(MU/MU/IN)", "32 Stunden", "32, davon 4 permanent", "32 Schritt", "1 Jahr", "Lebewesen (Verstorbene)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("TALISMANVERANKERUNG", "(KL/IN/CH)", "8 Stunden", "16, davon 4 permanent", "Berührung", "sofort", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("TAUBENGESTALT", "(MU/KL/IN)", "30 Minuten", "8", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("TEMPELWEIHE", "(MU/IN/CH)", "8 Stunden", "32, davon 8 permanent", "8 Schritt", "permanent", "Objekte (Tempel)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("TRAUMBILD", "(KL/IN/CH)", "5 Minuten", "8", "Berührung", "bis zum Ende des nächsten Traums des Ziels oder bis der Borongeweihte geweckt wird", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("TRAUMGESICHT", "(MU/IN/CH)", "5 Minuten", "8", "4 Schritt", "QSx10 Minuten", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("TRAVIASWACHGAENSE", "(CH/CH/CH)", "30 Minuten", "8", "selbst", "QS*2 Stunden", "Objekte (Herdfeuer)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("UNBESCHWERTEWANDERUNG", "(MU/IN/KO)", "5 Minuten", "4", "selbst", "1 Tag", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("UNTOTEERSCHAFFEN", "(MU/IN/CH)", "16 Stunden", "4/8/16/32/64 für Größenkategorie winzig/klein/mittel/groß/riesig, davon 0/1/2/4/8 permanent", "Berührung", "QS Wochen", "Lebewesen (Verstorbene)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("VERBLASSENDEERINNERUNG", "(MU/IN/CH)", "5 Minuten", "8", "Berührung", "1 Jahr", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("VERGESSEN", "(MU/IN/CH)", "30 Minuten", "8", "Berührung", "QS Tage", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("WAFFENFLUCH", "(MU/IN/KO)", "30 Minuten", "8/16/32 für Geschosse, Dolche und Raufen-Waffen/alle übrigen Waffen/Zweihandwaffen", "Berührung", "QSx3 Stunden", "Profane Objekte (Waffen)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("WEGWEISER", "(KL/IN/CH)", "5 Minuten", "8", "selbst", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("WEIHEDESHEIMS", "(MU/KL/IN)", "5 Minuten", "8", "Berührung", "QS Stunden", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("WIDDERGESTALT", "(MU/KL/IN)", "30 Minuten", "8", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("WIEDERHERSTELLUNG", "(MU/FF/KO)", "30 Minuten", "8", "Berührung", "sofort", "Profane Objekte")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("WINTERSCHLAF", "(MU/IN/CH)", "5 Minuten", "8", "Berührung", "QS Tage", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("WOLFSFLUCH", "(MU/KL/CH)", "2 Stunden", "16", "Berührung", "QS*3 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("WOLFSGESTALT", "(MU/KL/IN)", "30 Minuten", "8", "selbst", "QSx3 Stunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ZUFLUCHT", "(IN/CH/KO)", "5 Minuten", "8 pro Person", "Berührung", "6 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ZWERGISCHEVERBRUEDERUNG", "(MU/IN/CH)", "5 Minuten", "16", "Berührung", "30 Minuten", "Kulturschaffende (Zwerge)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ZWERGWALGESTALT", "(MU/KL/IN)", "30 Minuten", "16", "selbst", "QSx3 Stunden", "Lebewesen")));
        };
    }
}
