package com.example.WebProject.DSA;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;

import com.example.WebProject.Repository.DSAKarmaRepository;

public class DSAKarmaDatabase {
    private static final Logger log = LoggerFactory.getLogger(DSAKarmaDatabase.class);

    @Bean
    CommandLineRunner initDatabase(DSAKarmaRepository repository) {
        return args -> {
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ANGRIFFSLUST", "(MU/MU/IN)", "2 Aktionen", "8", "8 Schritt", "10 KR", "Wesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ANGRIFFSWELLE", "(MU/IN/KO)", "2 Aktionen", "16", "32 Schritt", "sofort", "Wesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("AUGEDESJAEGERS", "(MU/IN/CH)", "4 Aktionen", "8", "selbst", "1 Stunde", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("AUSNUECHTERN", "(KL/IN/CH)", "4 Aktionen", "4", "Berührung", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BANNDERDUNKELHEIT", "(MU/KL/CH)", "1 Aktionen", "4 + 2 pro Minute", "selbst", "aufrechterhaltend", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BANNDERFURCHT", "(IN/CH/CH)", "2 Aktionen", "8", "Berührung", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BANNDERGOETTLICHENGABEN", "(KL/IN/CH)", "2 Aktionen", "8", "Berührung", "QSx10 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BANNDESLICHTS", "(MU/KL/CH)", "4 Aktionen", "16 +8 pro 5 Minuten", "selbst", "aufrechterhaltend", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BANNWIDERUNTOTE", "(MU/KL/CH)", "2 Aktionen", "8", "8 Schritt", "sofort", "Untote, außer Vampire")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BANNSTRAHL", "(MU/IN/CH)", "4 Aktionen", "16", "16 Schritt", "sofort", "Dämonen, Kulturschaffende (Paktierer mit entblößtem Dämonenmal)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BANNZONE", "(MU/IN/CH)", "4 Aktionen", "4 +2 pro 5 KR", "4 Schritt", "aufrechterhaltend", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BAERENHAUT", "(IN/CH/KO)", "2 Aktionen", "8", "selbst", "QSx2 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BEFEHLDESSCHAMANEN", "(MU/KL/CH)", "2 Aktionen", "16", "4 Schritt", "QS KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BEFREIUNGDESGEISTES", "(MU/IN/CH)", "4 Aktionen", "8", "Berührung", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BEGNADETERREITER", "(MU/IN/CH)", "2 Aktionen", "8", "selbst", "2 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BERAUSCHEN", "(MU/CH/KO)", "8 Aktionen", "8", "8 Schritt", "15 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BESAENFTIGUNG", "(MU/KL/CH)", "2 Aktionen", "2", "8 Schritt", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BESCHEIDENHEIT", "(MU/KL/CH)", "4 Aktionen", "4", "8 Schritt", "QS Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BESCHWOERUNGDERGEMEINENDIENERDESRATTENKINDES", "(MU/CH/KO)", "4 Aktionen", "8", "8 Schritt", "sofort", "Dämonen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BLENDSTRAHL", "(MU/KL/IN)", "1 Aktionen", "4", "8 Schritt", "QS in Kampfrunden", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BLENDUNG", "(MU/KL/CH)", "8 Aktionen", "16", "4 Schritt", "QSx5 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BLICKAUFDENMEERESGRUND", "(KL/IN/IN)", "1 Aktionen", "4", "selbst", "QSx2 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BLICKDESHEILERS", "(KL/IN/CH)", "4 Aktionen", "4", "selbst", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BLITZSCHLAG", "(MU/IN/CH)", "4 Aktionen", "16", "16 Schritt", "sofort", "Wesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BLUTIGERZORN", "(MU/IN/CH)", "2 Aktionen", "16", "8 Schritt", "10 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BLUTIGESSIEGEL", "(MU/IN/CH)", "8 Aktionen", "16", "Berührung", "QSx100 Jahre", "Objekte (Buch)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BLUTZOLL", "(MU/IN/CH)", "2 Aktionen", "16", "selbst", "QSx2 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BODENWEIHE", "(MU/IN/CH)", "4 Aktionen", "8", "8 Schritt", "QSx10 Minuten", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BOTSCHAFTAUSDERTIEFE", "(MU/IN/CH)", "16 Aktionen", "8", "selbst", "QS/2 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BRAZORAGHSKRIEGER", "(MU/MU/IN)", "2 Aktionen", "8", "8 Schritt", "QSx2 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("BUECHERSUCHE", "(KL/KL/IN)", "16 Aktionen", "4", "selbst", "sofort", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("DAEMONENWALL", "(MU/KL/CH)", "1 Aktionen", "4", "selbst", "5 Minuten", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("DELPHINRUF", "(KL/IN/CH)", "4 Aktionen", "16", "selbst", "15 Minuten", "Tiere (Delphine)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("DESEINENBEZAUBERNDERSPHAERENKLANG", "(IN/CH/CH)", "1 Aktionen", "8", "8 Schritt", "QSx3 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("DOPPELGAENGER", "(MU/KL/IN)", "8 Aktionen", "16", "selbst", "QSx5 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("EHRENHAFTIGKEIT", "(MU/IN/CH)", "4 Aktionen", "8", "8 Schritt", "QSx3 in Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("EHRLICHERVERTRAG", "(KL/IN/CH)", "4 Aktionen", "8", "selbst", "2 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("EISBAERENRUF", "(MU/IN/CH)", "4 Aktionen", "16", "selbst", "15 Minuten", "Tiere(Eisbären)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ENTFESSELUNG", "(MU/KL/IN)", "2 Aktionen", "8", "4 Schritt", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ENTSTELLTESAMTLITZ", "(MU/IN/CH)", "4 Aktionen", "8", "8 Schritt", "2 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ENTZIFFERN", "(KL/KL/IN)", "8 Aktionen", "4", "selbst", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ERDBEBEN", "(MU/KL/IN)", "4 Aktionen", "16", "16 Schritt", "5 KR", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ERMUTIGUNG", "(MU/IN/CH)", "4 Aktionen", "8", "Berührung", "QSx3 Minuten", "Kulturschaffende, übernatürliche Wesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ERNUECHTERUNG", "(MU/KL/CH)", "2 Aktionen", "4", "selbst", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ERREGENDERRAUSCH", "(MU/IN/KO)", "8 Aktionen", "4", "selbst", "15 Minuten, danach wirkt Rauschmittel nicht mehr", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ERTRINKEN", "(MU/KL/KO)", "2 Aktionen", "4", "8 Schritt", "5 KR", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ERWACHEN", "(MU/IN/CH)", "2 Aktionen", "4", "16 Schritt", "sofort", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ERZENEOPFERGABE", "(MU/IN/CH)", "8 Aktionen", "8", "Berührung", "sofort", "Profane Objekte (Metalle und Steine)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FALLINSNICHTS", "(MU/IN/GE)", "1 Aktionen", "4", "selbst", "QSx9 KR", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FESSELNDESBAND", "(MU/IN/CH)", "1 Aktionen", "8", "16 Schritt", "QS KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FEUERWALL", "(MU/KL/CH)", "2 Aktionen", "16", "selbst", "5 Minuten", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FLUGECHSENRUF", "(MU/IN/CH)", "4 Aktionen", "16", "selbst", "15 Minuten", "Tiere (Flugechsen)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FREUNDSCHAFTLICHESAUFTRETEN", "(IN/CH/CH)", "4 Aktionen", "8", "selbst", "10 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FRIEDFERTIGKEIT", "(MU/IN/CH)", "4 Aktionen", "4 +2 pro 2 KR", "selbst", "aufrechterhaltend", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FRIEDVOLLEAURA", "(MU/IN/CH)", "1 Aktionen", "8", "selbst", "QSx3 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FRIEDVOLLERRAUSCH", "(MU/IN/CH)", "2 Aktionen", "8", "16 Schritt", "5 KR", "Kultruschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FROSTSTURM", "(MU/IN/CH)", "8 Aktionen", "8 +4 pro 5 Minuten", "selbst", "aufrechterhaltend", "selbst")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FURCHTEINFLOESSENDETIERGEISTER", "(MU/IN/CH)", "2 Aktionen", "8", "selbst", "5 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("FURCHTRESISTENZ", "(MU/CH/KO)", "1 Aktionen", "8", "selbst", "QSx5 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GEBIETERDERFLAMMEN", "(MU/KL/IN)", "4 Aktionen", "4 +2 pro Minute", "selbst", "aufrechterhaltend", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GEFÜHLSKÄLTE", "(MU/IN/CH)", "4 Aktionen", "8", "selbst", "QS Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GEISTDESSTRATEGEN", "(MU/KL/IN)", "1 Aktionen", "8", "16 Schritt", "5 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GEISTERBLICK", "(MU/IN/CH)", "2 Aktionen", "4 +2 pro Minute", "selbst", "aufrechthaltend", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GEISTERFALLE", "(MU/IN/CH)", "8 Aktionen", "16", "8 Schritt", "sofort", "Geister")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GELDWECHSEL", "(KL/IN/FF)", "1 Aktionen", "1", "Berührung", "1 Jahr", "Objekte")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GESEGNETERRAUSCH", "(MU/IN/CH)", "8 Aktionen", "4", "Berührung", "QSx30 Minuten", "Profane Objekte (Rauschmittel)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GESPUERFUERDASGOETTLICHE", "(MU/IN/CH)", "16 Aktionen", "16", "Berührung", "sofort", "Objekte")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GETREIDEWACHSTUM", "(KL/IN/CH)", "16 Aktionen", "4", "Berührung", "sofort", "Pflanze (landwirtschaftlich genutztes Getreide)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GIFTBANN", "(KL/IN/CH)", "4 Aktionen", "8", "4 Schritt", "sofort", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GNADENSTOSS", "(MU/IN/CH)", "2 Aktionen", "8", "Berührung", "4 +QS/2 KR", "Geweihte Objekte (Marbodolch)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GOLDENEHAND", "(KL/IN/CH)", "4 Aktionen", "8", "Berührung", "QS Stunden", "Profane Objekte (maximal Apfelgröße)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GOLDENERUESTUNG", "(MU/KL/IN)", "1 Aktionen", "4 für RS 1, 8 für RS 2, 16 für RS 3", "selbst", "QSx3 Minuten", "Wesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GOETTLICHEKLINGE", "(MU/KL/IN)", "2 Aktionen", "8", "Berührung", "QSx2 KR", "Objekte (profane Objekt, Waffen)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GOETTLICHEVERSTAENDIGUNG", "(MU/IN/CH)", "4 Aktionen", "8", "selbst", "selbst", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GOETTLICHERFINGERZEIG", "(KL/IN/IN)", "4 Aktionen", "8", "selbst", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GOETTLICHERRAUSCH", "(MU/IN/CH)", "8 Aktionen", "8", "selbst", "QSx3 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("GOETTLICHESZEICHEN", "(IN/IN/CH)", "4 Aktionen", "4", "4 Schritt", "sofort", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HAIRUF", "(MU/IN/CH)", "4 Aktionen", "16", "selbst", "15 Minuten", "Tiere (Streifenhaie)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HAUCHDESELEMENTS", "(MU/KL/CH)", "1 Aktionen", "8", "8 Schritt", "sofort", "Alle")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HEILIGERBEFEHL", "(MU/KL/CH)", "4 Aktionen", "16", "4 Schritt", "QSx2 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HEILIGESLIEBESSPIEL", "(MU/IN/CH)", "8 Aktionen", "4", "Berührung", "QSx30 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HEILSAMEQUELLE", "(KL/IN/CH)", "8 Aktionen", "8", "Berührung", "QS Minuten", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HEILSEGEN", "(KL/IN/CH)", "16 Aktionen", "1 pro LeP, mindestens 4", "Berührung", "sofort", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HELDENKRAFT", "(MU/IN/CH)", "2 Aktionen", "8", "selbst", "5 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HELFENDEHAND", "(KL/IN/CH)", "16 Aktionen", "8", "Berührung", "sofort (maximal 1 Woche)", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HERBEIRUFUNGDERHEERSCHARENDESRATTENKINDESRATTEN", "(MU/IN/CH)", "1 Aktionen", "8", "32 Schritt", "QSx3 Tage", "Tiere (Ratten)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HERBEIRUFUNGDERHEERSCHARENDESRATTENKINDESSCHAKALE", "(MU/IN/CH)", "2 Aktionen", "16", "32 Schritt", "QS Tage", "Tiere (Schakale)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HERBEIRUFUNGDERHEERSCHARENDESRATTENKINDESVAMPIRFLEDERMAEUSE", "(MU/IN/CH)", "1 Aktionen", "8", "32 Schritt", "QSx3 Tage", "Tiere (Vampirfledermaeuse)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HERBEIRUFUNGDERHEERSCHAFENDESRATTENKINDESWOLFSSPINNEN", "(MU/IN/CH)", "2 Aktionen", "16", "32 Schritt", "QS Tage", "Tiere (wolfsspinnen)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HERBEIRUFUNGVONTAIRACHSDIENERNNEBELKRAEHEN", "(MU/IN/CH)", "2 Aktionen", "8", "32 Schritt", "QS Tage", "Tiere (Nebelkrähen)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HERRDERFLAMMEN", "(MU/IN/CH)", "8 Aktionen", "8", "selbst", "QSx30 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("HILFREICHESEELE", "(MU/IN/CH)", "4 Aktionen", "4", "8 Schritt", "QS Schritt", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("INNERERUHE", "(MU/KL/IN)", "4 Aktionen", "8", "selbst", "5 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("JAGUARRUF", "(MU/IN/CH)", "4 Aktionen", "16", "selbst", "15 Minuten", "Tiere (Jaguare)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KAELTEEXPLOSION", "(MU/IN/KO)", "2 Aktionen", "8", "16", "sofort", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KAMPFGESCHICK", "(MU/IN/KO)", "1 Aktionen", "4", "selbst", "QSx2 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KLARERGEIST", "(MU/KL/IN)", "4 Aktionen", "8", "Berührung", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KLEIDUNGSCHAMAELEON", "(KL/IN/CH)", "2 Aktionen", "4", "Berührung", "QS Stunden", "Objekte (Kleidung)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KLEINEWINDHOSE", "(MU/CH/KO)", "1 Aktionen", "8", "16 Schritt", "sofort", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KLEINERBANNWIDERUNTOTE", "(MU/MU/CH)", "1 Aktionen", "4", "8 Schritt", "sofort", "Untote (Vampire sind immun)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KLEINERBANNSTRAHL", "(MU/IN/CH)", "2 Aktionen", "8", "16 Schritt", "sofort", "Dämonen, Kulturschaffende (Paktierer mit entblößtem Dämonenmal)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KRAFTVOLLERKOERPER", "(MU/IN/KO)", "4 Aktionen", "8", "selbst", "QSx5 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KRANKHEITENVORBEUGEN", "(IN/IN/CH)", "8 Aktionen", "8", "selbst", "QS Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KRANKHEITSBANN", "(KL/IN/CH)", "4 Aktionen", "8", "4 Schritt", "sofort", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("KRIEGSFARBEN", "(MU/IN/KO)", "2 Aktionen", "4", "selbst", "5 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("LAUTLOS", "(IN/IN/GE)", "4 Aktionen", "4 +2 pro Minute", "selbst", "aufrechterhaltend", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("LEBENSSCHUTZ", "(MU/KL/IN)", "2 Aktionen", "8", "Berührung", "sofort", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("LEVTHANISCHERLIEBHABER", "(MU/IN/CH)", "4 Aktionen", "8", "selbst", "QS Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("LITURGIESCHILD", "(MU/KL/CH)", "2 Aktionen", "4", "selbst", "10 Minuten", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("LUSTERZEUGEN", "(MU/IN/CH)", "1 Aktionen", "4", "4 Schritt", "QSx3 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MACHTDESLEVTHAN", "(MU/CH/KO)", "4 Aktionen", "16", "selbst", "QSx3 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MAECHTIGERANGRIFF", "(MU/IN/KO)", "2 Aktionen", "8", "selbst", "QSx3 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MAGIEANALYSE", "(KL/KL/IN)", "32 Aktionen", "16", "Berührung", "sofort", "Objekte, Wesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MAGIEBANN", "(KL/IN/CH)", "4 Aktionen", "8 bzw 16 für Zone", "Berührung", "sofort", "Alle")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MAGIESCHUTZ", "(MU/IN/CH)", "4 Aktionen", "8 +4 pro 10 Minuten", "selbst", "aufrechterhaltend", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MAGIESICHT", "(KL/IN/IN)", "2 Aktionen", "4", "8 Schritt", "1 Minute", "Lebewesen, Objekte")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MAGIESPIEGEL", "(MU/KL/IN)", "2 Aktionen", "8", "selbst", "QS KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MAMMUTRUF", "(MU/IN/CH)", "4 Aktionen", "32", "selbst", "15 Minuten", "Tiere (Mammuts)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MASKE", "(KL/IN/CH)", "4 Aktionen", "8", "selbst", "30 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MAUEREINSTURZ", "(MU/IN/CH)", "4 Aktionen", "16", "4 Schritt", "sofort", "Objekte (Mauer)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MEERESUNGEHEUERVERTREIBEN", "(MU/IN/CH)", "16 Aktionen", "16 bis groß, 32 für riesig", "16 Schritt", "sofort", "Lebewesen (Meeresungeheuer)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MITDUMMHEITSCHLAGEN", "(KL/IN/CH)", "2 Aktionen", "8", "Berührung", "2 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MONDSICHT", "(KL/KL/IN)", "4 Aktionen", "2 +1 pro 10 Minuten", "selbst", "aufrechterhaltend", "Wesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MONDSILBERZUNGE", "(KL/IN/CH)", "1 Aktionen", "8", "selbst", "QSx3 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("MOTIVATION", "(MU/IN/CH)", "4 Aktionen", "4", "Berührung", "2 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("NAMENLOSEKAELTE", "(KL/IN/CH)", "4 Aktionen", "16", "selbst", "30 Minuten", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("NAMENLOSERASEREI", "(MU/IN/CH)", "4 Aktionen", "16", "8 Schritt", "sofort", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("NAMENLOSEZWEIFEL", "(MU/IN/CH)", "4 Aktionen", "16", "16 Schritt", "QSx3 Tage", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("NAMENLOSESVERGESSEN", "(KL/IN/CH)", "2 Aktionen", "8", "Berührung", "QSx3 Tage", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("NABELKRAEHENSCHWARM", "(MU/KL/IN)", "2 Aktionen", "8", "selbst", "12 Stunden", "Kulturschaffende (nur Schamane selbst)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("NUMINORUSFESSELN", "(MU/KL/KK)", "2 Aktionen", "8", "8 Schritt", "QS +1", "Lebewesen")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("OBARANSBLENDUNG", "(MU/KL/CH)", "4 Aktionen", "16", "16 Schritt", "QSx5 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("OBJEKTSEGEN", "(MU/IN/CH)", "4 Aktionen", "4", "Berührung", "QSx3 Stunden", "Objekte")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("OBSESSION", "(KL/IN/CH)", "4 Aktionen", "8", "Berührung", "30 Minuten", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("OFFENLEGUNGDESGEISTES", "(KL/IN/CH)", "2 Aktionen", "8 +4 pro 30 Sekunden", "Berührung", "aufrechterhaltend", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("OGERRUF", "(KL/IN/CH)", "4 Aktionen", "16", "selbst", "QS Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("OPFERGANG", "(MU/KO/KK)", "4 Aktionen", "16", "selbst", "ein Kampf, maximal 2 Stunden", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("ORTDERRUHE", "(MU/KL/IN)", "8 Aktionen", "4", "4 Schritt", "QSX3 Stunden", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("PECHUNDSCHWEFEL", "(MU/KL/CH)", "2 Aktionen", "8", "16 Schritt", "sofort", "Alle")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("PERAINESGNADE", "(IN/CH/FF)", "2 Aktionen", "8", "Berührung", "QS KR", "'Objekte (Samenkorn)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("PFLANZENWUCHS", "(KL/IN/CH)", "16 Aktionen", "8", "Berührung", "1 Jahr", "Pflanze")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("QUALLENHAUT", "(MU/KL/KK)", "2 Aktionen", "16", "selbst", "QSx3 KR", "Kulturschaffende")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("QUALLENRUF", "(MU/IN/CH)", "4 Aktionen", "16", "selbst", "15 Minuten", "Tiere (Quallen)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("RABENRUF", "(MU/KL/IN)", "16 Aktionen", "8", "QSx3 Meilen", "QSx3 Stunden", "Tiere")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("RATTENSCHWARM", "(MU/KL/IN)", "2 Aktionen", "8", "selbst", "13 Stunden", "Kulturschaffende (nur der geweihte selbst)")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("REGENBOGENBRUECKE", "(MU/IN/KO)", "4 Aktionen", "8", "selbst", "QSx3 Minuten", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("REINIGUNGDESBOESEN", "(MU/IN/CH)", "8 Aktionen", "8", "4 Schritt", "sofort", "Zone")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("RINDERRUF", "(MU/IN/CH)", "4 Aktionen", "16", "selbst", "15 Minuten", "Tiere ((Ongalo-) Rinder")));
            log.info("Preloading " + repository.save(new DSAKarmaTemplate("RUFDERHEIMAT", "(KL/IN/CH)", "8 Aktionen", "4", "selbst", "QSx30 Minuten", "Kulturschaffende")));
            
        };
    }
}
