package com.example.WebProject;

public enum DSASpells {
    ABLATIVUM("MU/KL/CH", 1, 8, "selbst", "5 Minuten", "Zone"),
    ABVENENUM("KL/IN/FF", 8, 4, "4 Schritt", "sofort", "Objekte"),
    ADLERAUGE("KL/IN/FF", 2, 4, "selbst", "aufrechterhaltend", "Wesen"),
    ADLERSCHWINGE("MU/IN/GE", 8, 8, "selbst", "aufrechterhaltend", "Kulturschaffende"),
    AEOLITO("KL/CH/KO", 1, 8, "16 Schritt", "sofort", "Wesen"),
    AEROFUGO("MU/KO/KK", 8, 16, "16 Schritt", "QSx2KR", "Zone"),
    AFFENARME("MU/KL/CH", 2, 4, "selbst", "10 Minuten", "Kulturschaffende"),
    AFFENRUF("MU/CH/CH", 4, 16, "8 Schritt", "20 KR oder bis zum Tod der Tiere", "Zone"),
    ALPGESTALT("MU/CH/GE", 1, 4, "8 Schritt", "QS Kampfrunden", "Lebewesen"),
    ALTISONUS("MU/CH/KO", 4, 8, "selbst", "QSx5 Minuten", "Wesen"),
    ANALYSARKANSTRUKTUR("KL/KL/IN", 32, 16, "Berührung", "sofort", "OBjekte, Wesen"),
    ANGSTAUSLOESEN("MU/CH/GE", 4, 16, "selbst", "QSx2KR", "Kulturschaffende"),
    AQUAFAXIUS("MU/KL/CH", 2, 8, "16 Schritt", "sofort", "alle"),
    AQUAQUERIS("IN/CH/KO", 2, 4, "8 Schritt", "sofort", "Lebewesen"),
    AQUASPHAERO("MU/KL/KO", 4, 32, "32 Schritt", "sofort", "Zone"),
    ARACHNEA("MU/IN/CH", 8, 16, "selbst", "QSx3 Stunden", "50 Schritt Radius"),
    ARACHOFAXIUS("MU/KL/CH", 2, 8, "16 Schritt", "sofort", "alle"),
    ARACHOSPHAERO("MU/KL/KO", 4, 32, "32 Schritt", "sofort", "Zone"),
    ARAMATRUTZ("KL/IN/FF", 1, 4, "selbst", "QSx3 Minuten", "Wesen"),
    AROMATIXILLUSIONIS("KL/IN/CH", 4, 4, "8 Schritt", "aufrechterhaltend", "3 SChritt Radius"),
    ATEMNOT("KL/CH/KO", 1, 4, "8 Schritt", "QS Kampfrunden", "Lebewesen"),
    ATTRIBUTOCH("KL/IN/CH", 8, 8, "Berührung", "aufrechterhaltend", "Kulturschaffende"),
    ATTRIBUTOFF("KL/IN/FF", 8, 8, "Berührung", "aufrechterhaltend", "Kulturschaffende"),
    ATTRIBUTOGE("KL/IN/GE", 8, 8, "Berührung", "aufrechterhaltend", "Kulturschaffende"),
    ATTRIBUTOIN("KL/IN/IN", 8, 8, "Berührung", "aufrechterhaltend", "Kulturschaffende"),
    ATTRIBUTOKL("KL/KL/IN", 8, 8, "Berührung", "aufrechterhaltend", "Kulturschaffende"),
    ATTRIBUTOKO("KL/IN/KO", 8, 8, "Berührung", "aufrechterhaltend", "Kulturschaffende"),
    ATTRIBUTOKK("KL/IN/KK", 8, 8, "Berührung", "aufrechterhaltend", "Kulturschaffende"),
    ATTRIBUTOMU("KL/IN/MU", 8, 8, "Berührung", "aufrechterhaltend", "Kulturschaffende"),
    AUFWECKEN("MU/IN/CH", 2, 4, "16 Schritt", "sofort", "Lebewesen"),
    AUGEDESLIMBUS("MU/IN/KK", 16, 32, "32 Schritt", "QS KR", "Zone"),
    AURADERERSCHÖPFUNG("MU/KL/CH", 2, 16, "selbst", "sofort", "Kulturschaffende"),
    AUREOLUS,
    AURISILLUSIONIS,
    AVILEA,
    AXXELERATURS,
    AENGSTELINDERN,
    BALSAMSALABUNDE,
    BANDUNDFESSEL,
    BANNBALADIN,
    BASALTLEIB,
    BLICKAUFSWESEN,
    BLICKINDIEGEDANKEN,
    BLINDHEIT,
    BLITZDICHFIND,
    BLITZBALL,
    BOESERBLICK,
    BRANDUNGSLEIB,
    BRENNENDERHASS,
    CHAMAELIONI,
    CLAUDIBUS,
    CORPOFESSO,
    CORPOFRIGO,
    CRYPTOGRAHO,
    DAEMONENBANN,
    DAEMONENSCHILD,
    DAEMONISCHESVERGESSEN,
    DEBILITATIO,
    DESINTEGRATURS,
    DISRUPTIVO,
    DORNENWAND,
    DRACHENLEIB,
    DUNKELHEIT,
    DUPLICATUS,
    ECLIPTIFACTUS,
    EICHENLEIB,
    EIGENEaENGSTE,
    EIGENEDUMMHEIT,
    EINFLUSSBANN,
    EISENROST,
    EISESKAELTEKAEMPFERHERZ,
    EISPFEIL,
    EISWAND,
    ELEMENTARBANN,
    ELFENSTIMME,
    ERINNERUNGVERLASSEDICH,
    ERSCHOEPFUNGENLINDERN,
    ERZPFEIL,
    EULENRUF,
    EXPOSAMI,
    FALKENAUGE,
    FAVILLUDO,
    FEDERLEIB,
    FEENSTAUB,
    FESSELFELD,
    FEUERPEIL,
    FIRNLAUF,
    FISCHFLOSSE,
    FLAMMENWAND,
    FLEDERMAUSRUF,
    FLIMFLAM,
    FORAMEN,
    FORTIFEX,
    FRIGIFAXIUS,
    FRIGISPHAERO,
    FROSTLEIB,
    FULMINICTUS,
    GARDIANUM,
    GEDANKENBILDER,
    GEFUNDEN,
    GEISTERESSENZ,
    FIGTHAUT,
    GLUTLAUF,
    GRANITUNDMARMOR,
    GROSSEGEIER,
    GROSSEVERWIRRUNG,
    HALLUZINATION,
    HARMLOSEGESTALT,
    HASELBUSCH,
    HEILUNGSBANN,
    HELLSICHTBANN,
    HEPTAGRAMMA,
    HERRUEBERDASTIERREICH,
    HERZSCHLAGRUHE,
    HEXAGRAMMA,
    HEXENGALLE;
    HEXENHOLZ,
    HEXENKNOTEN,
    HEXENKRALLEN,
    HEXENSPEICHEL,
    HILFREICHEPFOTE,
    HILFREICHESCHWINGE,
    HILFREICHEtATZE,
    HIMMELSLAUF,
    HOELLENPEIN,
    HORNISSENRUF,
    HORRIPHOBUS,
    HUMOFAXIUS,
    HUMOSPHAERO,
    HUMUSPFEIL,
    INGIFAXIUS,
    IGNISPHAERO,
    IGNORANTIA,
    ILLUSIONSBANN,
    IMPERAVI,
    IMPERSONA,
    INVENDIO,
    INVERCANO,
    INVINCULO,
    INVOCATIOMINIMA,
    KARNIFILO,
    KATZENAUGEN,
    KATZENRUF,
    KLARUMPURUM,
    KRABBELNDERSCHRECKEN,
    KRAFTDESHUMUS,
    KRAFTDESTIERES,
    KRAEHENRUF,
    KROETENRUF,
    KROETENSPRUNG,
    KULMINATIO,
    KUSCH,
    LASTDESALTERS,
    LEVTHANSFEUER,
    LUFTPFEIL,
    LUNGEDESLEVIATAN,
    MALDERERSCHOEPFUNG,
    MALDERSCHWAECHE,
    MANIFESTO,
    MANUSILLUSIONIS,
    MANUSMIRACULA,
    MEMORANS,
    MENETEKEL,
    MINIMUSREDUCTIBUS,
    MOTORICUS,
    NEBELFORM,
    NEBELWAND,
    NUNTIOVOLO,
    OBJECTOBSCURO,
    OBJECTOFIXO,
    OBJECTOVOCO,
    OBJECTBANN,
    OCULUSASTRALIS,
    OCULUSILLUSIONIS,
    OCULUSARCANUM,
    OKTAGRAMMA,
    ORCANOFAXIUS,
    ORCANOSPHAERO,
    PANDAEMONIUM,
    PANIKUEBERKOMMEEUCH,
    PAPAGEIENRUF,
    PARALYSIS,
    PENETRIZZEL,
    PENTAGRAMMA,
    PESTILENZERSPUEREN,
    PESTODEM,
    PHYSIOSTABILIS,
    PLUMBUMBARUM,
    PROJECTIMAGO,
    PROTECTIONIS,
    PSYCHOSTABILIS,
    RADAU,
    REFLECTIMAGO,
    REGENERATIO,
    REPTILEA,
    RESPONDAMI,
    SALANDER,
    SANFTERFALL,
    SANFTMUT,
    SAPEFACTA,
    SATUARISHERRLICHKEIT,
    SCHIMMERNDERSCHILD,
    SCHLANGENRUF,
    SCHLECHTEAUSSTRAHLUNG,
    SCHLEIERDERUNWISSENHEIT,
    SCHMERZENLINDERN,
    SCHUPPENHAUT,
    SCHWARZUNDROT,
    SCHWARZERSCHRECKEN,
    SEELENTIERERKENNEN,
    SEIDENZUNGE,
    SENSATTACCO,
    SENIBAR,
    SERPENTIALIS,
    SILENTIUM,
    SINESIGIL,
    SKELETTARIUS,
    SOLIDIRID,
    SOMNIGRAVIS,
    SPHAERENBANN,
    SPINNENLAUF,
    SPINNENRUF,
    SPURLOS,
    STANDFEST,
    STEINWAND,
    STILLSTAND,
    STURMDERVERUNSICHERUNG,
    STURMWAND,
    SUMPFSTRUDEL,
    SUMUSELIXIERE,
    TAUBHEIT,
    TELEKINESEBANN;
    TEMPORALBANN,
    TEMPUSSTASIS,
    TIEREBESPRECHEN,
    TIERGEDANKEN,
    TRANSVERSALIS,
    UNENTFLAMMBARKEIT,
    UNGESCHICKT,
    VERUNSICHERUNG,
    VERWANDLUGNSBANN,
    VIPERNBLICK,
    VISIBILI,
    VOGELZWITSCHERN,
    WARMESGEFIERE,
    WASSERATEM,
    WASSERPFEIL,
    WELLEDERREINIGUNG,
    WELLEDESSCHMERZES,
    WELLENLAUF,
    WELLENWAND,
    WINDHOSE,
    WINDSTILLE,
    WIPFELLAUF,
    WOGEDERVERSTEINERUNG,
    WOLFSTATZE,
    WUESTENLAUF,
    ZAUBERPFERDHERBEIRUFEN,
    ZITTERFINGER;
    ZORNDERELEMENTE,
    ZUNGEBETAEUBEN,
    ZWEIFELSCHUEREN,
    ZWINGTANZ;

    private String Probe;
    private int Zd;
    private int AsP;
    private String Reichweite;
    private String Wd;
    private String Ziel;

    DSASpells(String Probe, int Zd, int AsP, String Reichweite, String Wd, String Ziel){
        this.Probe = Probe;
        this.Zd = Zd;
        this.AsP = AsP;
        this.Reichweite = Reichweite;
        this.Wd = Wd;
        this.Ziel = Ziel;
    }
}