package com.example.WebProject;

public enum DSASpells {

    //Magische Handlungen
    AUFMERKSAMERWAECHTER("IN/CH/FF", 1800, "8", "Sichtweite des Tieres", "QSx3 Stunden", "Profane Objekte (Tierbild)"),
    AUFGEBLASEN("IN/CH/KO", 4, "8", "8 Schritt", "QS Minuten", "Lebewesen"), 
    AUSBRUCHUNTERDRÜCKTERGEFÜHLE("MU/IN/CH", 0, "8", "Sichtweite", "QS Tage", "Kulturschaffende"),
    AENGSTEMEHREN("MU/IN/CH", 0, "14", "Opfer", "QSx3 Tage", "Kulturschaffende"),
    BANNZEICHENDERGEISTERURNE("MU/IN/CH", 2, "12", "selbst", "QS Monate/QSx5 Minuten", "Geist"),
    BANNZEICHENDESDAEMONENGEFAESSES("MU/IN/CH", 2, "16 für niedere Dämonen, 28 für Gehörnte bis zu 5 Hörnern, 40 für Dämonen mit mehr als 5 Hörnern", "selbst", "QS Monate/QSx5 Minuten", "Dämonen"),
    BANNZEICHENWIDERWESENHEIT("MU/MU/CH", 2, "18 gegen Dämonen, 12 gegen Daimonide, Chimären, Untote, Geister, Feen und Spinnen", "selbst", "QS Monate/QSx5 Minuten", "Dämonen. Feen, Daimonide, Chimären, Geister, Spinnen, Untote"),
    BANNZEICHENWIDERGIFT("KL/IN/CH", 1, "8", "selbst", "QS Monate/QSx5 Minuten", "Gifte"),
    BANNZEICHENWIDERSCHNEEUNDEIS("MU/MU/IN", 4, "12", "selbst", "QS MOnate/QSx5 Minuten", "Eis, Schnee"),
    BANNZEICHENWIDERSTÜRME("MU/IN/IN", 2, "10", "selbst", "QS Monate/QSx15 Minuten", "Gebäude"),
    BANNZEICHENWIDERZAUBEREI("MU/IN/CH", 1, "16", "selbst", "QS Monate/QSx2 Minuten", "Lebewesen"),
    BANNZEICHENWIDERZERSTOERUNG("MU/IN/KO", 2, "8, 12 oder 16", "selbst", "QS Monate/QSx5 KR", "Objekt"),
    BEISSAUFGRANIT("KL/IN/FF", 0, "14", "Opfer", "QSx3 Tage", "Kulturschaffende"),
    BEUTE("KL/IN/CH", 0, "14", "Opfer", "QSx3 Tage", "Kulturschaffende"),
    BLUTTRINKEN("MU/IN/CH", 0, "3", "Berührung", "sofort", "Kulturschaffende"),
    BRAZORAGHSHIEB("IN/KO/KK", 0, "8", "Berührung", "QSx2 KR", "Kulturschaffende"),
    DICHTERUNDDENKER("KL/IN/CH", 2, "8", "4 Schritt", "QS Minuten", "Kulturschaffende"),
    DURCHFESTEMATERIE("IN/IN/KO", 0, "4 +2 pro KR", "selbst", "QSx2 KR", "Kulturschaffende"),
    ELEMENTARERVERBUENDETER("MU/IN/CH", 300, "8", "selbst", "sofort", "Elementare (Elementargeister)"),
    ERINNERUNGSMELODIE("KL/IN/IN", 0, "1 pro 5 Minuten", "selbst", "so lange die erinnerte Szene Dauert", "Kulturschaffende"),
    FELLWECHSEL("MU/IN/KO", 0, "14", "Opfer", "QSx3 Tage", "Kulturschaffende"),
    FIGURDERSCHMERZEN("MU/IN/CH", 0, "8", "selbst", "QS/2 Tage", "selbst"),
    FLUCHDERPESTILZEN("MU/KL/CH", 0, "8", "Sichtweite", "bis zum Ende der Krankheit, maximal QSx3 Tage", "Kulturschaffende"),
    FLUCHDERSCHLAFLOSIGKEIT("KL/IN/CH", 0, "8", "Sichtweite", "QS Tage", "Kulturschaffende"),
    FREUNDSCHAFTSLIED("IN/CH/CH", 0, "4 pro Stunde, 1 permantenter bei letzter Strophe", "zwei Personen", "ewig", "Kulturschaffende"),
    FRIEDENSLIED("MU/IN/CH", 4, "2 pro 5 Minuten", "QSx3 Schritt", "bis zum Ende des Kampfes", "Zone"),
    GESCHMACKSSINNNEHMEN("IN/CH/KO", 0, "7", "Opfer", "QSx3 Wochen", "Kulturschaffende"),
    GESTALTAUSRAUCH("IN/CH/FF", 300, "4/8/12/16 für winziges/kleines/mittleres/großes Wesen", "1 Schritt", "QS Stunden", "Zone"),
    GESTANKANHEFTEN("MU/IN/CH", 0, "14", "Opfer", "QSx3 Tage", "Kulturschaffende"),
    GOBLINBANNZONE("MU/IN/CH", 4, "4 +2 pro 5 KR", "4 Schritt", "aufrechterhaltend", "Zone"),
    GOBLINEXORZISMUS("MU/IN/CH", 28800, "32", "4 Schritt", "sofort", "Dämonen, Geister"),
    GOBLINGEISTERFALLE("MU/IN/CH", 8, "16", "8 Schritt", "sofort", "Nicht Lebende (Geister)"),
    GOBLINGEISTHEILUNG("KL/CH/KO", 300, "4", "Berührung", "24 Stunden", "Lebewesen"),
    GOBLINHAUCH("MU/KL/CH", 1, "8", "8 Schritt", "sofort", "alle"),
    GOBLINKRIEGSMATSCH("MU/IN/KO", 2, "4", "selbst", "5 KR", "Kulturschaffende"),
    GOBLINPFLANZENWUCHS("KL/IN/CH", 16, "8", "Berührung", "1 Jahr", "Pflanze"),
    GOBLINREGENTANZ("MU/IN/CH", 1800, "16", "32 Schritt", "QSx30 Minuten", "Zone"),
    GOBLINTABUZONE("KL/IN/CH", 9600, "16", "8 Schritt", "1 Monat", "Zone"),
    GOBLINZUFLUCHT("IN/CH/KO", 300, "8 pro Person", "Berührung", "6 Stunden", "Kulturschaffende"),
    GROSSERSPRUNG("IN/GE/KO", 0, "4 +2 pro KR", "selbst", "aufrechterhaltend", "Kulturschaffende"),
    HAGELSCHLAG("MU/IN/CH", 0, "21", "Opfer", "QSx15 Minuten", "Kulturschaffende"),
    HARTEHAUT("MU/IN/KO", 0, "6", "selbst", "QSx2 KR", "Kulturschaffende"),
    HEXENSCHUSS("IN/FF/KO", 0, "14", "Opfer", "QSx3 Stunden", "Kulturschaffende"),
    HOLTERDIPOLTER("IN/CH/FF", 4, "16", "selbst", "QSx2 KR", "Zone"),
    HUNGERWECKEN("MU/CH/KO", 0, "7", "Opfer", "QSx3 Tage", "Kulturschaffende"),
    IMMUNITAETGEGENHITZE("MU/IN/CH", 0, "5", "selbst", "QS Stunden", "Kulturschaffende"),
    IMMUNITAETGEGENKAELTE("MU/IN/CH", 0, "5", "selbst", "QS Stunden", "Kulturschaffende"),
    JUCKPULVER("MU/IN/CH", 2, "4", "4 Schritt", "5 KR", "Kulturschaffende"),
    JUCKREIZVERURSACHEN("MU/KL/IN", 0, "14", "Opfer", "QSx3 Stunden", "Kulturschaffende"),
    KACKOPHONIEDESWAHNSINNS("MU/KL/CH", 0, "8 pro 5 Minuten", "QSx3 Schritt", "Länge des Liedes", "Lebewesen, Zone"),
    KAMPFFAEHIGKEITENVERBESSERN("MU/IN/KO", 0, "2 +1 pro KR", "selbst", "aufrechterhaltend", "Kulturschaffende"),
    KOBOLDGESCHENK("IN/CH/FF", 8, "8", "4 Schritt", "QSx2 Minuten", "Kulturschaffende"),
    KORNFAEULE("KL/IN/KO", 0, "14", "Opfer", "sofort", "Kulturschaffende"),
    KRAFTAUSSCHMERZEN("KL/IN/KO", 0, "16", "Berührung", "QSx2 KR", "Kulturschaffende"),
    KROETENKUSS("MU/CH/CH", 0, "14", "Opfer", "QSx3 Stunden", "Kulturschaffende"),
    KRISTALLDERHERRSCHAFT("MU/KL/CH", 0, "8 + Kosten des Zaubers", "je des Zaubers", "je nach Zauber", "Kulturschaffende"),
    LACHDICHGESUND("IN/CH/FF", 2, "8", "4 Schritt", "5 Minuten", "Kulturschaffende"),
    LACHKRAMPF("IN/CH/FF", 4, "16", "8 Schritt", "QS Minuten", "Kulturschaffende"),
    LANGERLULATSCHKLEINERDOTZ("IN/CH/GE", 4, "8", "8 Schritt", "QS Minuten", "Kulturschaffende"),
    LIEDDERABWEHRDAEMONISCHERMAECHTE("IN/CH/CH", 0, "6", "50 Schritt", "10 Minuten nach Ende des Liedes", "Zone"),
    LIEDDERERHOLUNG("IN/CH/CH", 0, "3 pro Zuhörer", "20 Schritt", "sofort", "Kulturschaffende"),
    LIEDDERKLARHEIT("IN/CH/CH", 0, "3 pro Zuhörer", "20 Schritt", "sofort", "Kulturschaffende"),
    LIEDDERLIEDER("MU/IN/CH", 1200, "12", "20 Schritt", "sofort", "Kulturschaffende"),
    LIEDDERPFLANZEN("IN/CH/CH", 0, "2", "Pflanze", "sofort", "Pflanze"),
    LIEDDERREINHEIT("MU/IN/CH", 0, "8 pro 5 KR", "QSx2 Schritt", "sofort", "Dämonen"),
    LIEDDERTIERWAHRNEHMUNG("IN/CH/CH", 0, "4 pro Minute", "QS Meilen", "sofort", "Tiere"),
    LIEDDESHEILSCHLAFS("IN/IN/CH", 0, "8", "20 Schritt", "sofort", "Kulturschaffende"),
    LIEDDESSCHMERZES("MU/KL/IN", 0, "8 pro 5 Minuten", "QSx3 Schritt", "Länge des Liedes", "Lebewesen"),
    LIEDDESTROSTES("IN/CH/CH", 0, "3 pro Zuhörer", "20 Schritt", "sofort", "Kulturschaffende, Zone"),
    LIEDDESWINDGEFLUESTERS("IN/IN/CH", 0, "4", "selbst", "sofort", "Kulturschaffende"),
    LIEDDESZAUBERSCHUTZES("IN/CH/CH", 0, "6", "selbst", "bis Schildstärke 0 oder 30 Minuten", "Kulturschaffende"),
    MACHTÜBERSCHLAFWANDLER("MU/KL/IN", 0, "32", "Opfer", "QS Stunden", "Kulturschaffende"),
    MAECHTIGERPATRONRUFTIERART("IN/KO/KK", 0, "je nach Tierart", "selbst", "QSx5 Minuten", "Kulturschaffende"),
    MEISTERMINDERERGEISTER("MU/IN/CH", 2, "8", "16 Schritt", "QSx3 Minuten", "Elementare (Mindergeister)"),
    MELODIEDERKUNSTFERTIGKEIT("IN/IN/CH", 0, "4 pro Stunde", "selbst", "Liedlänge", "Kulturschaffende"),
    MIESELAUNE("MU/IN/CH", 0, "7", "Opfer", "QSx3 Stunden", "Kulturschaffende"),
    MITBLINDHEITSCHLAGEN("KL/IN/CH", 0, "21", "Opfer", "QSx30 Minuten", "Kulturschaffende"),
    MURKSUNDPATZ("IN/CH/FF", 2, "8", "8 Schritt", "QSx3 KR", "Kulturschaffende"),
    NACKEDEI("KL/IN/FF", 4, "8", "8 Schritt", "sofort", "Objekte"),
    ORVAIKURIMSKRIEGSTROMMEL("IN/FF/KO", 1800, "16", "Berührung", "QSx3 Tage", "Profane Objekte (Trommeln)"),
    PATRONRUF("MU/IN/CH", 0, "4", "selbst", "30 KR", "Kulturschaffende"),
    PAPPERLAPAPP("IN/CH/FF", 4, "8", "selbst", "QSx2 Minuten", "Kulturschaffende"),
    PECHANDENHALSWUENSCHEN("KL/IN/CH", 0, "7", "Opfer", "QSx3 Tage", "Kulturschaffende"),
    PESTILENZ("MU/CH/GE", 0, "Stufe der Krankheit", "Opfer", "bis zum Ende der Krankheit, max QSx3 Tage", "Kulturschaffende"),
    SCHELMENKLEISTER("KL/IN/GE", 2, "8", "16 Schritt", "QSx2 KR", "Zone"),
    SCHELMENLAUNE("MU/IN/CH", 4, "8", "selbst", "QSx3 Minuten", "Kulturschaffende"),
    SCHELMENMASKE("IN/CH/GE", 4, "8", "selbst", "QSx3 Minuten", "Kulturschaffende"),
    SCHELMENRAUSCH("KL/IN/CH", 2, "8", "8 Schritt", "QSx3 Minuten", "Kulturschaffende"),
    SCHLACHTLIED("MU/IN/CH", 0, "1 pro KR", "QSx3 Schritt", "Länge des Lieds", "Zone, Kulturschaffende"),
    SCHLAFRAUBEN("KL/IN/CH", 0, "14", "Opfer", "QSx3 Tage", "Kulturschaffende"),
    SCHNELLERANGRIFF("MU/IN/GE", 0, "4 +2 pro KR", "selbst", "aufrechterhaltend", "Kulturschaffende"),
    SIEGELDERSEELENRUHE("IN/IN/CH", 2, "10", "selbst", "QS Monate/QSx5 Minuten", "Lebewesen"),
    SKLAVENLIED("MU/IN/CH", 0, "4 pro Minute", "QS Schritt", "Länge des Liedes", "Kulturschaffende"),
    SORGENLIED("MU/IN/IN", 300, "2 pro 5 Minuten", "bis zu Freund", "sofort", "Kulturschaffende"),
    STEINMACHT("MU/IN/KK", 0, "6", "Zone", "sofort", "Kulturschaffende"),
    STURMLIED("MU/IN/KO", 0, "2 pro Minute", "Qsx10 Schritt", "Länge des Liedes", "Zone"),
    TALENTVERBESSERUNG("IN/CH/KO", 0, "2 +1 pro Minute", "selbst", "aufrechterhaltend", "Kulturschaffende"),
    TAUSCHRAUSCH("IN/CH/FF", 2, "4", "8 Schritt", "sofort", "Objekte"),
    TIERGEISTSPRACHE("MU/IN/CH", 0, "8", "selbst", "QSx3 Minuten", "Kulturschaffende"),
    TIERKRAEFTE("MU/IN/KO", 0, "4 +2 pro 10 KR", "selbst", "aufrechterhaltend", "Kulturschaffende"),
    TIERVERWANDLUNG("MU/IN/KO", 0, "je nach Tierart", "selbst", "maximal QS Stunden", "Kulturschaffende"),
    TODESFLUCH("MU/IN/CH", 0, "21", "Opfer", "QSx3 Tage", "Kulturschaffende"),
    TRANKDESUNGEHINDERTENWEGES("IN/GE/KO", 7200, "8", "selbst", "QS/2 Tage", "Kulturschaffende"),
    TRUEMMERSCHLAG("MU/IN/KK", 0, "4 +2 pro KR", "selbst", "aufrechterhaltend", "Kulturschaffende"),
    UNBESCHADETERSTURZ("MU/IN/GE", 0, "6", "selbst", "5 Minuten", "Kulturschaffende"),
    UNERSCHOEPFLICH("IN/KO/KK", 0, "4", "selbst", "QS KR", "Kulturschaffende"),
    UNFRUCHTBARKEIT("IN/FF/KO", 0, "14", "Opfer", "QSx3 Wochen", "Kulturschaffende"),
    VERSCHWINDIBUS("IN/CH/FF", 1, "8", "Berührung", "QSx3 Minuten", "Objekte"),
    VIEHVERSTUEMMELUNG("IN/IN/KO", 0, "7", "Opfer", "QS Tage", "Kulturschaffende"),
    WARZENSPRIESSEN("IN/FF/KO", 0, "7", "Opfer", "QSx3 Tage", "Kulturschaffende"),
    WILDSCHWEINRUF("MU/IN/CH", 4, "16", "selbst", "15 Minuten", "Tiere (Wildschwein)"),
    WOLLUSTVERURSACHEN("IN/CH/KO", 0, "14", "Opfer", "QSx3 Stunden", "Kulturschaffende"),
    WURZELDESBLUTES("MU/MU/IN", 0, "8", "selbst", "24 Stunden", "Kulturschaffende"),
    ZAGIBUUBIGAZ("KL/CH/KK", 1, "4", "8 Schritt", "sofort", "profane Objekte"),
    ZAUBERMELODIE("MU/IN/CH", 3600, "8", "selbst", "bis zum nächsten Sonnenaufgang", "Kulturschaffende"),
    ZUNGELAEHMEN("KL/IN/CH", 0, "14", "Opfer", "QSx3 Stunden", "Kulturschaffende"),
    ZWEILINKEHAENDE("MU/IN/FF", 0, "7", "Opfer", "QSx3 Stunden", "Kulturschaffende"),

    //Zaubersprüche

    ABLATIVUM("MU/KL/CH", 1, "8", "selbst", "5 Minuten", "Zone"),
    ABVENENUM("KL/IN/FF", 8, "4", "4 Schritt", "sofort", "Objekte"),
    ADLERAUGE("KL/IN/FF", 2, "4", "selbst", "aufrechterhaltend", "Wesen"),
    ADLERSCHWINGE("MU/IN/GE", 8, "8", "selbst", "aufrechterhaltend", "Kulturschaffende"),
    AEOLITO("KL/CH/KO", 1, "8", "16 Schritt", "sofort", "Wesen"),
    AEROFUGO("MU/KO/KK", 8, "16", "16 Schritt", "QSx2KR", "Zone"),
    AFFENARME("MU/KL/CH", 2, "4", "selbst", "10 Minuten", "Kulturschaffende"),
    AFFENRUF("MU/CH/CH", 4, "16", "8 Schritt", "20 KR oder bis zum Tod der Tiere", "Zone"),
    ALPGESTALT("MU/CH/GE", 1, "4", "8 Schritt", "QS Kampfrunden", "Lebewesen"),
    ALTISONUS("MU/CH/KO", 4, "8", "selbst", "QSx5 Minuten", "Wesen"),
    ANALYSARKANSTRUKTUR("KL/KL/IN", 32, "16", "Berührung", "sofort", "OBjekte, Wesen"),
    ANGSTAUSLOESEN("MU/CH/GE", 4, "16", "selbst", "QSx2KR", "Kulturschaffende"),
    AQUAFAXIUS("MU/KL/CH", 2, "8", "16 Schritt", "sofort", "alle"),
    AQUAQUERIS("IN/CH/KO", 2, "4", "8 Schritt", "sofort", "Lebewesen"),
    AQUASPHAERO("MU/KL/KO", 4, "32", "32 Schritt", "sofort", "Zone"),
    ARACHNEA("MU/IN/CH", 8, "16", "selbst", "QSx3 Stunden", "50 Schritt Radius"),
    ARACHOFAXIUS("MU/KL/CH", 2, "8", "16 Schritt", "sofort", "alle"),
    ARACHOSPHAERO("MU/KL/KO", 4, "32", "32 Schritt", "sofort", "Zone"),
    ARAMATRUTZ("KL/IN/FF", 1, "4", "selbst", "QSx3 Minuten", "Wesen"),
    AROMATIXILLUSIONIS("KL/IN/CH", 4, "4", "8 Schritt", "aufrechterhaltend", "3 SChritt Radius"),
    ATEMNOT("KL/CH/KO", 1, "4", "8 Schritt", "QS Kampfrunden", "Lebewesen"),
    ATTRIBUTOCH("KL/IN/CH", 8, "8", "Berührung", "aufrechterhaltend", "Kulturschaffende"),
    ATTRIBUTOFF("KL/IN/FF", 8, "8", "Berührung", "aufrechterhaltend", "Kulturschaffende"),
    ATTRIBUTOGE("KL/IN/GE", 8, "8", "Berührung", "aufrechterhaltend", "Kulturschaffende"),
    ATTRIBUTOIN("KL/IN/IN", 8, "8", "Berührung", "aufrechterhaltend", "Kulturschaffende"),
    ATTRIBUTOKL("KL/KL/IN", 8, "8", "Berührung", "aufrechterhaltend", "Kulturschaffende"),
    ATTRIBUTOKO("KL/IN/KO", 8, "8", "Berührung", "aufrechterhaltend", "Kulturschaffende"),
    ATTRIBUTOKK("KL/IN/KK", 8, "8", "Berührung", "aufrechterhaltend", "Kulturschaffende"),
    ATTRIBUTOMU("KL/IN/MU", 8, "8", "Berührung", "aufrechterhaltend", "Kulturschaffende"),
    AUFWECKEN("MU/IN/CH", 2, "4", "16 Schritt", "sofort", "Lebewesen"),
    AUGEDESLIMBUS("MU/IN/KK", 16, "32", "32 Schritt", "QS KR", "Zone"),
    AURADERERSCHÖPFUNG("MU/KL/CH", 2, "16", "selbst", "sofort", "Kulturschaffende"),
    AUREOLUS("IN/CH/FF", 4, "2", "Berührung", "QS Stunden", "Objekte"),
    AURISILLUSIONIS("KL/IN/CH", 4, "4", "8 Schritt", "aufrechterhaltend", "Radius von 5 Schritt"),
    AVILEA("MU/IN/CH", 8, "16", "selbst", "QSx3 Stunden", "50 Schritt mit Zauberndem als beweglichem Mittelpunkt"),
    AXXELERATURS("KL/IN/FF", 1, "8", "Berührung", "QSx5Kampfrunden", "Lebewesen"),
    AENGSTELINDERN("MU/IN/CH", 4, "8", "Berührung", "sofort", "Kulturschaffende"),
    BALSAMSALABUNDE("KL/IN/FF", 16, "1 pro LP", "Berührung", "sofort", "Kulturschaffende"),
    BANDUNDFESSEL("KL/CH/KK", 16, "8", "8 Schritt", "QSx2 Stunden", "Lebewesen"),
    BANNBALADIN("MU/IN/CH", 4, "8", "4 Schritt", "QSx3 Minuten", "Kulturschaffende, übernatürliche Wesen"),
    BASALTLEIB("MU/KL/KK", 8, "8", "selbst", "QS Minuten", "Lebewesen"),
    BLICKAUFSWESEN("KL/IN/CH", 4, "4", "8 Schritt", "sofort", "Wesen"),
    BLICKINDIEGEDANKEN("MU/KL/IN", 4, "8", "4 Schritt", "aufrechterhaltend", "Kulturschaffende, übernatürliche Wesen"),
    BLINDHEIT("KL/IN/CH", 16, "16", "8 Schritt", "QSx5 Minuten", "Kulturschaffende"),
    BLITZDICHFIND("MU/IN/CH", 1, "4", "8 Schritt", "QS KR", "Lebewesen"),
    BLITZBALL("MU/KL/CH", 2, "16", "selbst", "sofort", "Kulturschaffende"),
    BOESERBLICK("MU/IN/CH", 2, "8", "8 Schritt", "QS KR", "Kulturschaffende"),
    BRANDUNGSLEIB("MU/IN/GE", 8, "8", "selbst", "QS Minuten", "Lebewesen"),
    BRENNENDERHASS("MU/IN/CH", 8, "16", "4 Schritt", "QS Minuten", "Kulturschaffende"),
    CHAMAELIONI("IN/CH/GE", 2, "8", "selbst", "QS Minuten", "Kulturschaffende"),
    CLAUDIBUS("KL/IN/FF", 2, "4", "Berührung", "30 Minuten", "Objecte"),
    CORPOFESSO("KL/IN/KO", 2, "8", "8 Schritt", "QS x 3 in KR", "Lebewesen"),
    CORPOFRIGO("KL/CH/KO", 1, "8", "16 Schritt", "sofort", "Wesen"),
    CRYPTOGRAHO("KL/KL/IN",16, "2", "Berührung", "QS Monate", "Objekte"),
    DAEMONENBANN("MU/CH/KO", 4, "8", "8 Schritt", "sofort", "alle"),
    DAEMONENSCHILD("MU/KL/CH", 1, "4", "selbst", "5 Minuten", "Zone"),
    DAEMONISCHESVERGESSEN("MU/KL/IN", 4, "8", "Berührung", "QSx3 Minuten", "Kulturschaffende"),
    DEBILITATIO("MU/KL/IN", 2, "16", "8 Schritt", "QSx3 KR", "Zone"),
    DESINTEGRATURS("KL/CH/KK", 8, "16", "8 Schritt", "sofort", "Objekt"),
    DISRUPTIVO("MU/KL/CH", 8, "8 + 4 pro 5 Mintuen", "selbst", "aufrechterhaltend", "Zone"),
    DORNENWAND("MU/KL/CH", 4, "16", "8 Schritt", "30 KR", "Zone"),
    DRACHENLEIB("MU/KL/GE", 8, "8", "selbst", "QS Minuten", "Lebewesen"),
    DUNKELHEIT("MU/KL/CH", 8, "16", "selbst", "aufrechterhaltend", "Zone"),
    DUPLICATUS("KL/IN/CH", 2, "4 pro Doppelgänger", "Berührung", "QSx3 KR", "Lebewesen"),
    ECLIPTIFACTUS("MU/IN/CH", 2, "4", "selbst", "aufrechterhaltend", "Lebewesen"),
    EICHENLEIB("MU/KL/KK", 8, "8", "selbst", "QS Minuten", "Lebewesen"),
    EIGENEAENGSTE("MU/IN/CH", 4, "8", "Berührung", "15 Minuten", "Lebewesen"),
    EIGENEDUMMHEIT("MU/IN/CH", 4, "8", "Berührung", "15 Mintuen", "Lebewesen"),
    EINFLUSSBANN("KL/IN/CH", 4, "8 bzw. 16 für Zone", "8 Schritt", "sofort", "alle"),
    EISENROST("KL/CH/GE", 4, "8", "4 Schritt", "sofort", "profane Objekte"),
    EISESKAELTEKAEMPFERHERZ("MU/IN/KO", 4, "8", "selbst", "10 KR", "Kulturschaffende"),
    EISPFEIL("IN/CH/FF", 2, "2", "Berührung", "QSx3KR", "Objekte"),
    EISWAND("MU/KL/CH", 4, "16", "8 Schritt", "30 KR", "Zone"),
    ELEMENTARBANN("IN/CH/KO", 4, "8", "8 Schritt", "sofort", "alle"),
    ELFENSTIMME("IN/CH/KO", 2, "4", "4 Schritt", "QSx3Kampfrunden", "Lebewesen"),
    ERINNERUNGVERLASSEDICH("MU/IN/CH", 4, "8", "Berührung", "QSx5 Minuten", "Kulturschaffende"),
    ERSCHOEPFUNGENLINDERN("MU/IN/CH", 4, "8", "Berührung", "sofort", "Kultruschaffende"),
    ERZPFEIL("IN/CH/FF", 2, "2", "Berührung", "QSx3 KR", "Objekte"),
    EULENRUF("MU/CH/CH", 4, "16", "8 Schritt", "bis zum Tod der Tiere, maximal 20 KR", "Zone"),
    EXPOSAMI("KL/IN/CH", 2, "4", "QSx20 Schritt", "10 KR", "Lebewesen"),
    FALKENAUGE("MU/KL/IN", 2, "4", "Berührung", "bis zum nächsten Schuss, maximal QSx2 KR", "Lebewesen"),
    FAVILLUDO("IN/FF/CH", 1, "4", "selbst", "QS KR", "Kulturschaffende"),
    FEDERLEIB("MU/IN/GE", 8, "8", "selbst", "QS Minuten", "Lebewesen"),
    FEENSTAUB("MU/KL/CH", 4, "4", "1 Schritt", "sofort", "Objekte"),
    FESSELFELD("MU/CH/KO", 4, "16", "16 Schritt", "QSx2 KR", "Zone"),
    FEUERPEIL("IN/CH/FF", 2, "2", "Berührung", "QSx2 KR", "Objekte"),
    FIRNLAUF("MU/KL/GE", 16, "8", "selbst", "WSx3 Minuten", "Kulturschaffende"),
    FISCHFLOSSE("MU/IN/GE", 8, "8", "selbst", "aufrechterhaltend", "Kulturschaffende"),
    FLAMMENWAND("MU/KL/CH", 4, "16", "8 Schritt", "30 KR", "Zone"),
    FLEDERMAUSRUF("MU/CH/CH", 4, "16", "8 Schritt", "bis zum Tod der Tiere, maximal jedoch 20 KR", "Zone"),
    FLIMFLAM("MU/KL/CH", 1, "2 +1 pro Stunde", "8 Schritt", "aufrechterhaltend", "Zone"),
    FORAMEN("KL/IN/FF", 2, "8", "Berührung", "5 Minuten", "Objekte (Schlösser)"),
    FORTIFEX("MU/IN/KO", 4, "16", "8 Schritt", "30 KR", "Zone"),
    FRIGIFAXIUS("MU/KL/CH", 4, "8", "16 Schritt", "sofort", "alle"),
    FRIGISPHAERO("MU/KL/KO", 4, "32", "32 Schritt", "sofort", "Zone"),
    FROSTLEIB("MU/KL/GE", 8, "8", "selbst", "QS Minuten", "Lebewesen"),
    FULMINICTUS("KL/IN/KO", 1, "8", "8 Schritt", "sofort", "Lebewesen"),
    GARDIANUM("MU/KL/CH", 1, "min 4", "selbst", "5 Minuten", "Zone"),
    GEDANKENBILDER("IN/CH/KO", 2, "4", "4 Schritt", "QSx3 KR", "Lebewesen"),
    GEFUNDEN("KL/IN/GE", 8, "2", "selbst", "sofort", "Objekte"),
    GEISTERESSENZ("MU/KL/CH", 4, "4", "1 Schritt", "sofort", "Objekte"),
    GIFTHAUT("MU/IN/KO", 2, "8", "selbst", "QSx3KR", "Kulturschaffende"),
    GLUTLAUF("MU/KL/GE", 16, "8", "selbst", "QSx3 Minuten", "Kulturschaffende"),
    GRANITUNDMARMOR("CH/KL/IN", 4, "32", "Berührung", "QSx3 Stunden", "Kulturschaffende"),
    GROSSEGEIER("MU/IN/CH", 2, "8", "Berührung", "QSx15 Minuten", "Lebewesen"),
    GROSSEVERWIRRUNG("MU/KL/CH", 2, "8", "8 Schritt", "QSx3 Minuten", "Lebewesen"),
    HALLUZINATION("KL/IN/CH", 16, "8", "4 Schritt", "QSx3 Minuten", "Kulturschaffende"),
    HARMLOSEGESTALT("KL/IN/CH", 4, "8", "selbst", "aufrechterhaltend", "Wesen"),
    HASELBUSCH("IN/CH/FF", 16, "4", "2 Schritt", "1 Tag", "Pflanze"),
    HEILUNGSBANN("KL/CH/FF", 4, "8", "8 Schritt", "sofort", "alle"),
    HELLSICHTBANN("KL/IN/CH", 4, "8", "8 Schritt", "sofort", "alle"),
    HEPTAGRAMMA("MU/KL/CH", 8, "8", "8 Schritt", "sofort", "Beseelte, Geister"),
    HERRUEBERDASTIERREICH("MU/IN/CH", 4, "KL des Tieres in AsP", "8 Schritt", "QS Tage", "Tiere"),
    HERZSCHLAGRUHE("MU/CH/KK", 4, "16", "Berührung", "QSx3 Kampfrunden", "Lebewesen"),
    HEXAGRAMMA("MU/KL/CH", 8, "16", "8 Schritt", "sofort", "Elementare"),
    HEXENGALLE("KL/IN/KO", 1, "4", "selbst", "sofort", "Wesen"),
    HEXENHOLZ("KL/FF/KK", 1, "1 pro 5 Stein, min 4 Asp + hälfte Aktivierungskosten pro 5 Minuten", "16Schritt", "aufrechterhaltend", "Objekte"),
    HEXENKNOTEN("MU/IN/CH", 4, "16", "16 Schritt", "QSx10 KR", "Zone"),
    HEXENKRALLEN("MU/IN/KO", 1, "4", "selbst", "QSx3 Minuten", "Wesen"),
    HEXENSPEICHEL("IN/CH/FF", 2, "4", "Berührung", "QS KR", "Kulturschaffende"),
    HILFREICHEPFOTE("MU/IN/CH", 16, "8", "64 Schritt", "QSx10 Minuten", "Tiere (Säugetiere)"),
    HILFREICHESCHWINGE("MU/IN/CH", 16, "8", "64 Schritt", "QSx10 Minuten", "Tiere (Vögel)"),
    HILFREICHETATZE("MU/IN/CH", 16, "8", "64 Schritt", "QSx10 Minuten", "Tiere (Säugetiere)"),
    HIMMELSLAUF("MU/KL/GE", 16, "8", "selbst", "QSx3 Minuten", "Kulturschaffende"),
    HOELLENPEIN("MU/IN/CH", 4, "8", "Berührung", "5 Minuten", "Lebewesen"),
    HORNISSENRUF("MU/CH/CH", 4, "16", "8 Schritt", "bis zum Tod der Tiere, masimal 20 KR", "Zone"),
    HORRIPHOBUS("MU/IN/CH", 2, "8", "8 Schritt", "QSx3 Minuten", "Lebewesen"),
    HUMOFAXIUS("MU/KL/CH", 2, "8", "16 Schritt", "sofort", "alle"),
    HUMOSPHAERO("MU/KL/KO", 4, "32", "32 Schritt", "sofort", "Zone"),
    HUMUSPFEIL("IN/CH/FF", 2, "2", "Berührung", "QSx3 KR", "Objekte"),
    INGIFAXIUS("MU/KL/CH", 2, "8", "16 Schritt", "sofort", "alle"),
    IGNISPHAERO("MU/KL/KO", 4, "32", "32 Schritt", "sofort", "Zone"),
    IGNORANTIA("IN/CH/GE", 4, "8", "16 Schritt", "QS Minuten", "Kulturschaffende"),
    ILLUSIONSBANN("KL/IN/CH", 4, "8 bzw 16 bei Zone", "8 Schritt", "sofort", "alle"),
    IMPERAVI("MU/KL/CH", 16, "16", "Berührung", "QSx3 Minuten", "Kulturschaffende"),
    IMPERSONA("IN/CH/FF", 4, "4", "selbst", "aufrechterhaltend", "Kulturschaffende"),
    INCENDIO("KL/CH/KO", 1, "8", "16 Schritt", "sofort", "Wesen"),
    INVERCANO("MU/IN/FF", 1, "8", "selbst", "QS KR", "Kulturschaffende"),
    INVINCULO("KL/CH/KO", 1, "8", "16 Schritt", "5 KR", "Wesen"),
    INVOCATIOMINIMA("MU/CH/KO", 4, "4", "1 Schritt", "sofort", "Objekte"),
    KARNIFILO("MU/IN/CH", 4, "16", "8 Schritt", "QSx2 KR", "Kulturschaffende"),
    KATZENAUGEN("KL/IN/KO", 4, "2 + 1 pro 10 Minuten", "selbst", "aufrechthaltend", "Wesen"),
    KATZENRUF("MU/CH/CH", 4, "16", "8 Schritt", "bis zum Tod der Tiere, maximal 20 KR", "Zone"),
    KLARUMPURUM("KL/IN/CH", 4, "8", "4 Schritt", "sofort", "Lebewesen"),
    KRABBELNDERSCHRECKEN("MU/CH/FF", 2, "16", "4 Schritt", "10 KR", "Lebewesen"),
    KRAFTDESHUMUS("IN/CH/KO", 16, "4", "Berührung", "1 Tag", "Pflanzen (Baum)"),
    KRAFTDESTIERES("MU/IN/KO", 2, "4", "selbst", "5 KR", "Kulturschaffende"),
    KRAEHENRUF("MU/CH/CH", 4, "16", "8 Schritt", "bis zum Tod der Tiere, maximal 20 KR", "Zone"),
    KROETENRUF("MU/CH/CH", 4, "16", "8 Schritt", "bis zum Tod der Tiere, maximal 20 KR", "Zone"),
    KROETENSPRUNG("KL/IN/KO", 2, "2", "selbst", "sofort", "Lebewesen"),
    KULMINATIO("MU/IN/KO", 2, "8", "16 Schritt", "sofort", "alle"),
    KUSCH("MU/IN/CH", 1, "4", "8 Schritt", "QSx3 Minuten", "Tiere"),
    LASTDESALTERS("IN/CH/KO", 4, "8", "Berührung", "QS Stunden", "Kulturschaffende"),
    LEVTHANSFEUER("MU/IN/CH", 2, "8", "Berührung", "QS Stunden", "Kulturschaffende"),
    LUFTPFEIL("IN/CH/FF", 2, "2", "Berührung", "QSx3 KR", "Objekte"),
    LUNGEDESLEVIATAN("MU/IN/KO", 2, "4", "selbst", "QSx2 KR", "Lebewesen"),
    MALDERERSCHOEPFUNG("MU/IN/CH", 4, "8", "Berührung", "15 Minuten", "Lebewesen"),
    MALDERSCHWAECHE("MU/IN/CH", 4, "8", "Berührung", "15 Minuten", "Lebewesen"),
    MANIFESTO("MU/KL/CH", 4, "4", "1 Schritt", "sofort", "Objekte"),
    MANUSILLUSIONIS("KL/IN/CH", 4, "4", "8 Schritt", "aufrechterhaltend", "Zone"),
    MANUSMIRACULA("KL/FF/KK", 2, "4", "selbst", "aufrechterhaltend", "Wesen"),
    MEMORANS("KL/KL/IN", 4, "4", "selbst", "1 Jahr", "Kulturschaffende"),
    MENETEKEL("KL/CH/FF", 4, "2", "8 Schritt", "QSx30 Minuten", "Zone"),
    MINIMUSREDUCTIBUS("KL/CH/GE", 4, "16", "Berührung", "QSx3 Minuten", "Objekte (profan)"),
    MOTORICUS("KL/FF/KK", 2, "min 4 + Hälfte notwendige AsP pro 5 Minuten", "8 Schritt", "aufrechterhaltend", "Objekte"),
    NEBELFORM("MU/IN/KO", 4, "8", "selbst", "aufrechterhaltend", "Lebewesen"),
    NEBELWAND("MU/KL/CH", 2, "min 4", "16 Schritt", "QSx15 Minuten", "Zone"),
    NUNTIOVOLO("MU/KL/CH", 8, "4 + 1 AsP pro 10 Meilen", "4 Schritt", "sofort", "Dämonen"),
    OBJECTOBSCURO("KL/FF/KO", 4, "8", "Berührung", "aufrechterhaltend", "Objekte"),
    OBJECTOFIXO("MU/KL/KK", 2, "4", "Berührung", "QS Minuten", "Objekte"),
    OBJECTOVOCO("KL/IN/CH", 4, "4", "Berührung", "sofort", "Objekte"),
    OBJECTBANN("KL/IN/FF", 4, "8", "8 Schritt", "sofort", "alle"),
    OCULUSASTRALIS("KL/IN/CH", 2, "8", "selbst", "QSx3 Minuten", "Wesen"),
    OCULUSILLUSIONIS("KL/IN/CH", 4, "4", "8 Schritt", "aufrechterhaltend", "Radius von 3 Schritt"),
    OCULUSARCANUM("KL/IN/IN", 2, "4", "8 Schritt", "1 Minute", "Objekte, Wesen"),
    OKTAGRAMMA("MU/KL/CH", 8, "8", "8 Schritt", "sofort", "Feenwesen"),
    ORCANOFAXIUS("MU/KL/CH", 2, "8", "16 Schritt", "sofort", "alle"),
    ORCANOSPHAERO("MU/KL/KO", 4, "32", "32 Schritt", "sofort", "Zone"),
    PANDAEMONIUM("MU/CH/KK", 8, "16", "16 Schritt", "QSx3 KR", "Zone"),
    PANIKUEBERKOMMEEUCH("MU/KL/CH", 2, "16", "selbst", "sofort", "Kulturschaffende"),
    PAPAGEIENRUF("MU/CH/CH", 4, "16", "8 Schritt", "bis zum Tod der Tiere, maximal 20 KR", "Zone"),
    PARALYSIS("KL/IN/KO", 2, "8", "8 Schritt", "QSx3 Minuten", "Lebewesen"),
    PENETRIZZEL("MU/KL/IN", 2, "4 + 2 pro Minute", "selbst", "aufrechterhaltend", "alle"),
    PENTAGRAMMA("MU/KL/CH", 8, "16", "8 Schritt", "sofort", "Dämonen"),
    PESTILENZERSPUEREN("MU/KL/IN", 4, "8", "4 Schritt", "sofort", "Kulturschaffende"),
    PESTODEM("MU/IN/KO", 2, "16", "selbst", "sofort", "Lebewesen"),
    PHYSIOSTABILIS("KL/IN/FF", 8, "4 +2 pro 10 Minuten", "Berührung", "aufrechterhaltend", "Lebewesen"),
    PLUMBUMBARUM("MU/CH/GE", 2, "8", "8 Schritt", "5 KR", "Kulturschaffende"),
    PROJECTIMAGO("MU/IN/CH", 8, "8 + 1 pro zusätzlicher Meile", "Berührung", "QSx3 Minuten", "Kulturschaffende"),
    PROTECTIONIS("KL/KO/CH", 8, "8", "4 Schritt", "sofort", "Zauber"),
    PSYCHOSTABILIS("KL/IN/FF", 8, "4 +2 pro 10 Minuten", "Berührung", "aufrechterhaltend", "Lebewesen"),
    RADAU("KL/FF/KK", 2, "4 +2 pro KR", "16 Schritt", "aufrechterhaltend", "Objekte"),
    REFLECTIMAGO("KL/CH/FF", 4, "2", "4 Schritt", "QSx3 Minuten", "Objekte"),
    REGENERATIO("IN/CH/KO", 4, "4 +2 pro KR", "selbst", "aufrechterhaltend", "Lebewesen"),
    REPTILEA("MU/IN/CH", 8, "16", "selbst", "QSx3 Stunden", "50 Schritt mit Zauberer als beweglichem Mittelpunkt"),
    RESPONDAMI("MU/IN/CH", 2, "8", "Berührung", "QSx15 Minuten", "Lebewesen"),
    SALANDER("KL/IN/KO", 8, "16", "Berührung", "QSx3 Stunden", "Lebewesen"),
    SANFTERFALL("MU/IN/GE", 1, "4", "selbst", "QS Minuten", "Lebewesen"),
    SANFTMUT("MU/IN/CH", 2, "4", "8 Schritt", "QSx3 Minuten", "Tiere"),
    SAPEFACTA("KL/CH/FF", 4, "4", "selbst", "sofort", "Kulturschaffende"),
    SATUARISHERRLICHKEIT("KL/IN/KO", 4, "8", "selbst", "QSx3 Stunden", "Wesen"),
    SCHIMMERNDERSCHILD("MU/IN/KO", 1, "8", "selbst", "5 KR", "Kulturschaffende"),
    SCHLANGENRUF("MU/CH/CH", 4, "AsP", "8 Schritt", "bis zum Tod der Tiere, maximal 20 KR", "Zone"),
    SCHLECHTEAUSSTRAHLUNG("MU/IN/CH", 4, "8", "Berührung", "15 Minuten", "Lebewesen"),
    SCHLEIERDERUNWISSENHEIT("MU/IN/CH", 4, "4", "selbst", "QSx10 Minuten", "Kulturschaffende"),
    SCHMERZENLINDERN("MU/IN/CH", 4, "8", "Berührung", "sofort", "Kulturschaffende"),
    SCHUPPENHAUT("MU/IN/GE", 1, "2 +1 pro KR", "selbst", "aufrechterhaltend", "Kulturschaffende"),
    SCHWARZUNDROT("MU/CH/KO", 2, "16", "Berührung", "8 Stunden", "Kulturschaffende"),
    SCHWARZERSCHRECKEN("MU/IN/CH", 4, "4", "8 Schritt", "QS Stunden", "Kulturschaffende"),
    SEELENTIERERKENNEN("MU/IN/CH", 4, "8", "4 Schritt", "24 Stunden", "Kulturschaffende"),
    SEIDENZUNGE("KL/IN/CH", 2, "8", "4 Schritt", "5 Minuten", "Kulturschaffende"),
    SENSATTACCO("MU/IN/GE", 2, "8", "8 Schritt", "QSx2 KR", "Lebewesen"),
    SENIBAR("MU/IN/CH", 4, "8", "4 Schritt", "aufrechterhaltend", "Kulturschaffende"),
    SERPENTIALIS("MU/CH/GE", 2, "8 +4 pro 5 KR", "selbst", "aufrechterhaltend", "Kulturschaffende"),
    SILENTIUM("KL/FF/KK", 8, "4 +2 pro 5 Minuten", "selbst", "aufrechterhaltend", "Zone"),
    SINESIGIL("KL/IN/FF", 2, "4", "selbst", "QSx5 Minuten", "Kulturschaffende"),
    SKELETTARIUS("MU/KL/CH", 2, "8", "8 Schritt", "QSx2 Minuten", "Kulturschaffende"),
    SOLIDIRID("MU/IN/KO", 4, "8", "selbst", "QSx3 Minuten", "Zone"),
    SOMNIGRAVIS("MU/IN/CH", 2, "8", "8 Schritt", "QSx3 Minuten", "Lebewesen"),
    SPHAERENBANN("MU/IN/CH", 4, "8, bzw 16 für Zone", "8 Schritt", "sofort", "alle"),
    SPINNENLAUF("KL/IN/KO", 4, "4 +2 pro 5 Minuten", "selbst", "aurfrechterhaltend", "Lebewesen"),
    SPINNENRUF("MU/CH/CH", 4, "16", "8 Schritt", "bis zum Tod der Tiere, maximal 20 KR", "Zone"),
    SPURLOS("KL/FF/KK", 4, "4 +2 pro 5 Minuten", "selbst", "aufrechterhaltend", "Wesen"),
    STANDFEST("MU/IN/GE", 1, "4", "selbst", "QSx2 Minuten", "Kulturschaffende"),
    STEINWAND("MU/KL/CH", 4, "16", "8 Schritt", "30 KR", "Zone"),
    STILLSTAND("MU/IN/KO", 2, "16", "16 Schritt", "QSx3 KR", "Zone"),
    STURMDERVERUNSICHERUNG("MU/KL/CH", 2, "16", "selbst", "sofort", "Kulturschaffende"),
    STURMWAND("MU/KL/CH", 4, "16", "8 Schritt", "30 KR", "Zone"),
    SUMPFSTRUDEL("KL/IN/IN", 4, "8", "8 Schritt", "sofort", "Zone"),
    SUMUSELIXIERE("KL/IN/IN", 4, "8", "Berührung", "QS Jahren", "Objekte (Zutaten für Alchimica)"),
    TAUBHEIT("KL/IN/CH", 4, "4", "8 Schritt", "QSx5 Minuten", "Kulturschaffende"),
    TELEKINESEBANN("KL/IN/FF", 4, "8, bzw 16 für Zone", "8 Schritt", "sofort", "alle"),
    TEMPORALBANN("MU/IN/CH", 4, "8, bzw 16 für Zone", "8 Schritt", "sofort", "alle"),
    TEMPUSSTASIS("MU/KL/KK", 2, "32", "8 Schritt", "je nach Wunsch des Zauberers", "Zone"),
    TIEREBESPRECHEN("MU/IN/CH", 16, "1 pro LeP, min 4", "Berührung", "sofort", "Tiere"),
    TIERGEDANKEN("MU/IN/CH", 4, "4 +2 pro 30 Sekunden", "4 Schritt", "aufrechterhaltend", "Tiere"),
    TRANSVERSALIS("MU/CH/KO", 8, "8 +1 pro Meile", "selbst", "sofort", "Objekte, Wesen"),
    UNENTFLAMMBARKEIT("MU/IN/KO", 4, "4 +2 pro 10 Minuten", "selbst", "aufrechterhaltend", "Kulturschaffende"),
    UNGESCHICKT("MU/IN/CH", 4, "8", "Berührung", "15 Minuten", "Lebewesen"),
    VERUNSICHERUNG("MU/IN/CH", 4, "8", "Berührung", "15 Minuten", "Lebewesen"),
    VERWANDLUGNSBANN("KL/CH/FF", 4, "8, bzw 16 für Zone", "8 Schritt", "sofort", "alle"),
    VIPERNBLICK("MU/MU/CH", 4, "8 +4 pro 5 KR", "8 Schritt", "aufrechterhaltend, max 50 KR", "Kulturschaffende"),
    VISIBILI("KL/IN/KO", 4, "8 +4 pro 5 Minuten", "Berührung", "aufrechterhaltend", "Lebewesen"),
    VOGELZWITSCHERN("MU/IN/FE", 2, "4", "selbst", "QSx3 Minuten", "Zone"),
    WARMESGEFIERE("KL/CH/GE", 4, "2/4/8/16 für Gegenstand der Größe Tasse/Truhe/Tür/Burgtor", "4 Schritt", "QSx2 KR", "profane Objekte"),
    WASSERATEM("KL/IN/KO", 8, "4 +2 pro 5 Minuten", "Berührung", "aufrechterhaltend", "Lebewesen"),
    WASSERPFEIL("IN/CH/FF", 2, "2", "Berührung", "QSx3 KR", "Objekte"),
    WELLEDERREINIGUNG("MU/KL/KK", 4, "8", "selbst", "sofort", "Zone"),
    WELLEDESSCHMERZES("MU/KL/KK", 2, "16", "selbst", "sofort", "Kulturschaffende"),
    WELLENLAUF("MU/KL/GE", 16, "8", "selbst", "QSx3 Minuten", "Kulturschaffende"),
    WELLENWAND("MU/KL/CH", 4, "16", "8 Schritt", "30 KR", "Zone"),
    WINDHOSE("MU/IN/KK", 16, "32", "selbst", "QSx3 KR", "Zone"),
    WINDSTILLE("MU/IN/CH", 4, "4", "selbst", "QSx3 KR", "Zone"),
    WIPFELLAUF("MU/KL/GE", 16, "8", "selbst", "QSx3 Minuten", "Kulturschaffende"),
    WOGEDERVERSTEINERUNG("MU/KL/KO", 2, "16", "selbst", "sofort", "Kulturschaffende"),
    WOLFSTATZE("MU/IN/GE", 8, "8", "selbst", "aufrechterhaltend", "Kulturschaffende"),
    WUESTENLAUF("MU/KL/GE", 16, "8", "selbst", "QSx3 Minuten", "Kulturschaffende"),
    ZAUBERPFERDHERBEIRUFEN("KL/IN/CH", 16, "16", "4 Schritt", "sofort", "Lebewesen (Zauberpferd)"),
    ZITTERFINGER("MU/IN/CH", 4, "8", "Berührung", "15 Minuten", "Lebewesen"),
    ZORNDERELEMENTE("MU/KL/CH", 1, "8", "8 Schritt", "sofort", "alle"),
    ZUNGEBETAEUBEN("KL/IN/CH", 2, "8", "8 Schritt", "QSx5 Minuten", "Kulturschaffende"),
    ZWEIFELSCHUEREN("KL/IN/CH", 4, "8", "4 Schritt", "QS Stunden", "Kulturschaffende"),
    ZWINGTANZ("MU/KL/CH", 2, "16", "8 Schritt", "QS in KR", "Kulturschaffende");

    private String Probe;
    private int Zd;
    private String AsP;
    private String Reichweite;
    private String Wd;
    private String Ziel;

    DSASpells(String Probe, int Zd, String AsP, String Reichweite, String Wd, String Ziel){
        this.Probe = Probe;
        this.Zd = Zd;
        this.AsP = AsP;
        this.Reichweite = Reichweite;
        this.Wd = Wd;
        this.Ziel = Ziel;
    }
}